### ISSUE TITLE
UI Feature Flag Epic

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#15185]
Tracking issue to make the workflow board less busy:
* [x] https://github.com/vector-im/element-web/issues/8725 - remove/fix&hide e2ee icons
* [x] https://github.com/vector-im/element-web/issues/15172 - rageshakes
* [x] https://github.com/vector-im/element-web/issues/15173 - analytics
* [x] https://github.com/vector-im/element-web/issues/15174 - feedback
* [x] https://github.com/vector-im/element-web/issues/15175 - voip
* [x] https://github.com/vector-im/element-web/issues/15176 - url previews
* [x] https://github.com/vector-im/element-web/issues/15177 - integrations
* [x] https://github.com/vector-im/element-web/issues/15178 - flair
* [x] https://github.com/vector-im/element-web/issues/15179 - advanced
* [x] https://github.com/vector-im/element-web/issues/15180 - social
* [x] https://github.com/vector-im/element-web/issues/15181 - identity
* [x] https://github.com/vector-im/element-web/issues/15182 - communities
* [x] https://github.com/vector-im/element-web/issues/15183 - gifs
* [x] https://github.com/vector-im/element-web/issues/15184 - seshat web
* [x] https://github.com/vector-im/element-web/issues/15186 - e2ee forced on
* [x] https://github.com/vector-im/element-web/issues/15187 - 3pid login requirements
* [x] https://github.com/vector-im/element-web/issues/15188 - in-app account management
* [x] Documentation: https://github.com/vector-im/element-web/pull/15190

**Comment by turt2live** [comment]
I'm closing this out because all the issues are individually tracked on the board now
