### ISSUE TITLE
Matrix Spaces [MSC1772] support

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#15930]
- [x] Space creation from LLP
- [x] Space post-creation prompts to invite users/add rooms in mid panel
    - [x] Public space
    - [x] Private space
- [x] Room list filter by spaces:
    - [x] Home contains orphaned rooms
    - [x] Home contains all DMs
    - [x] Home contains all Favourites
    - [x] Filtered to a space contains rooms you are in from that space + DMs you have with users in that space
- [x] Space landing page
    - [x] Name
    - [x] Avatar
    - [x] Topic
    - [x] Member count
    - [x] Invite state
    - [x] Self-join state
    - [x] Inviting to spaces
- [x] Adding new rooms to spaces
- [x] Hide space homes from breadcrumbs?
- [x] Space settings
- [x] Space User Menu
    - [x] Invite leading to a share prompt
    - [x] Wire up Members button
- [x] Use unstable prefixes?
- [x] Add a space to a space (nested subspaces)
- [x] Right panel tweaks
    - [x] Space members
    - [x] Space User info
    - [x] 3pid panel
- [x] Adding existing rooms to spaces
    - [x] allow changing scope to a subspace here
    - [x] fix scrollable region
    - [x] busy & error states, confirm all pending design Qs
- [x] Sane auto-switching of the SpacePanel when you navigate between rooms otherwise, e.g using pills/breadcrumbs
- [x] Persist selected space(s) between refreshes [On device]
- [x] Notification dots on the SpacePanel buttons
    - [x] Match room intersection algorithm from room list
- [x] Left Panel `+` for adding rooms to spaces
    - [x] Disable based on perms within space with useful tooltips
- [x] Space invites show landing page
    - [x] selects the space in the LLP? conflicts with only showing joined spaces
    - [x] Server support: by default clients won't know its a space or its name/avatar which is jarring.
- [x] Default rooms preview in Space home
    - [x] Nested subspaces
- [x] Space room directory
    - [x] Nested subspaces
    - [x] Management of auto_join/remove
- [x] Theming
- [x] Sane handling of nested spaces without breaking in recursion
- [x] Accessibility
    - [x] Space Panel must be a well behaved treeview
    - [x] Room List must remain a well behaved treeview
    - [x] Space creation flow
    - [x] Space post-creation flow
 - [x] Hierarchies in the space panel
     - [x] With expand/collapse
     - [x] With the ability to view/select subspaces
 - [x] Show suggested rooms in the room list

Deferred:
 - [x] TBC: Home/All changes
- [ ] Support selecting multiple Spaces via shift-clicking
    - [ ] Room List show each selected space as distinct named "Rooms"-like sublist
- [ ] Instrumentation
- [ ] Optimisations to the store
- [x] Tests

Resolves https://github.com/vector-im/element-web/issues/15246 https://github.com/vector-im/element-web/issues/10802  https://github.com/vector-im/element-web/issues/12240 https://github.com/vector-im/element-web/issues/12658 https://github.com/vector-im/element-web/issues/13144 https://github.com/vector-im/element-web/issues/13257 https://github.com/vector-im/element-web/issues/14923 https://github.com/vector-im/element-web/issues/9970 https://github.com/vector-im/element-web/issues/10383 https://github.com/vector-im/element-web/issues/8951 https://github.com/vector-im/element-web/issues/8869 https://github.com/vector-im/element-web/issues/7340 https://github.com/vector-im/element-web/issues/7339 https://github.com/vector-im/element-web/issues/7010 https://github.com/vector-im/element-web/issues/6653 https://github.com/vector-im/element-web/issues/6646 https://github.com/vector-im/element-web/issues/6589 https://github.com/vector-im/element-web/issues/6517 https://github.com/vector-im/element-web/issues/6512 https://github.com/vector-im/element-web/issues/6497 https://github.com/vector-im/element-web/issues/6229 https://github.com/vector-im/element-web/issues/5870 https://github.com/vector-im/element-web/issues/5750 https://github.com/vector-im/element-web/issues/5743 https://github.com/vector-im/element-web/issues/5240 https://github.com/vector-im/element-web/issues/5228 https://github.com/vector-im/element-web/issues/6193 https://github.com/vector-im/element-web/issues/16267

Split into the following milestones:
1. https://github.com/vector-im/element-web/issues/16203
2. https://github.com/vector-im/element-web/issues/16204
3. https://github.com/vector-im/element-web/issues/16205
4. https://github.com/vector-im/element-web/issues/16206
5. https://github.com/vector-im/element-web/issues/16207
6. https://github.com/vector-im/element-web/issues/16208

**Comment by bwindels** [comment]
More things to do:

 - [ ] Space panel with drag to resize mechanic similar to room list
 - [ ] Hierarchies in the space panel
   - [ ] With expand/collapse
   - [ ] With the ability to view/select subspaces
 - [ ] Switching between ‘Show favourites for.. This space/all spaces’ in Favourites context menu
 - [ ] Switching between letterboxes & sticky headers in user settings
 - [ ] TBC: Home/All changes

**Comment by t3chguy** [comment]
(added to the main checkboxes above so it tracks properly on the board)

**Comment by MurzNN** [comment]
In testing interface prototype at https://riots.im/adhoc/spaces4 I got several pitfalls:
1. How to add room to space, with keeping it visible in default list of room (in "Home" space)?
2. Why I can't add DM rooms (People) to space? One of main applications for Spaces for me is to group long plain list of "People" rooms into groups like "Friends", "Work 1", "Project 2", "Sysadmins", etc.

**Comment by t3chguy** [comment]
https://riots.im/adhoc/spaces5/ is the latest testing build.

> How to add room to space, with keeping it visible in default list of room (in "Home" space)?

You can't. The Home space lists orphaned rooms, i.e ones which don't have another home.

> Why I can't add DM rooms (People) to space? One of main applications of Spaces for me is to group long plain list of "People" rooms into groups (like "Family", "Friends", "Work 1", "Project 2", "Sysadmins", etc), without informing them that I "group" them in my private space (so adding them to my private space as member is not suitable).

That is a fair point, its a tricky one because it makes sense for Spaces as Collections but doesn't make sense for either Workspaces or Community Spaces and we can't deterministically determine which one you are intentionally using it as.
Would be super confusing if #GamingSpace1 admin added a bunch of his DMs to the space for some reason.

**Comment by SimonBrandner** [comment]
I guess that for grouping people something like tags would be better. This is maybe something to consider while working on [contacts](https://github.com/vector-im/roadmap/issues/10)

**Comment by SimonBrandner** [comment]
![Screenshot_20210116_121203](https://user-images.githubusercontent.com/25768714/104810571-c80f9300-57f5-11eb-9b23-f614d601f3a9.png)
![Screenshot_20210116_121218](https://user-images.githubusercontent.com/25768714/104810572-c8a82980-57f5-11eb-94d4-6fdf9411da29.png)

I tried out the [testing build](https://riots.im/adhoc/spaces5/) and I'd like to comment on a few things. Maybe they are just implementation bugs but I can't tell. 

+ The theme button in the second menu should be in the account section and it should be moved to the right.
+ The menus have very different font sizes. I think the intention here was to make the menus the same size, but it feels very inconsistent...

I also think that having the space menu and the account menu on the same place may be a little confusing. Maybe it would be best to separate these two menus as Discord does it?

**Comment by MurzNN** [comment]
> > How to add room to space, with keeping it visible in default list of room (in "Home" space)?
> 
> You can't. The Home space lists orphaned rooms, i.e ones which don't have another home.

But most of people don't want to split the whole list by Spaces with missing to see "All the rooms" list, like implemented now. For this way we already have Discord and Slack, that cause you to always split between servers/workspaces, when you actively talking simultaneously in several spaces!

So the Matrix Spaces must be also the way to privately filter/group the whole list of rooms, not to split it by small sub-lists, and make people constantly switch between them to lookup "all unread messages".

> That is a fair point, its a tricky one because it makes sense for Spaces as Collections

Yes, one of main usage of Spaces (for me and my colleagues) is group current long list of people+rooms by parts, related to home/work, project1/project2, etc. And only second way is joining to shared Spaces for become a member of them. 

For what needs I must became a member of some workspace, eg "Linux admins" with 100+ rooms? For only see myself in member list and tell other about this? It's enough for me to have the bookmark to "Linux admins" Space somewhere in interface, that will be needed to rarely lookup the list of all rooms in space (and join to new interested rooms), and that's all.

At now we have Tags for this way of usage, that can solve this problem, but they still in Labs and have no integrated interface to manage, so isn't available for regular users! And I very afraid, that when Matrix Spaces interface will be published, the Matrix team will put aside the whole "Tags" feature to far-far future with decision "We implement Spaces, use them for grouping! Tags are legacy!".

About [contacts](https://github.com/vector-im/roadmap/issues/10) feature, it also too far from implementing, and will can solve only "grouping of personal contacts (users)" task, but not "personal grouping of people _and_ rooms together in personal groups".

The Spaces feature is very close to "Tags", so, please, try to implement the currently-unfinished "Tags" feature via Spaces too. For not confuse people, we can name the Spaces for personal grouping as "Personal space", maybe without ability to share it (or keep share, but with large red warning).

**Comment by Extarys** [comment]
@MurzNN Did you use MSN Messenger back in the day? It seems to me that you would prefer to categorize your contacts (and rooms) independently from what _they_ categorize you.

![image](https://user-images.githubusercontent.com/11581433/104818034-fa6bc100-57f2-11eb-876b-391d1c746702.png)
(Thanks duckduck)

I thought Spaces was more about a _discord_ feeling, To have people grouped together, on both ends.

**Comment by Glandos** [comment]
I have to support @MurzNN on this. My first expectation on Spaces was to finally be able to split between work and family. Both are on Matrix, I use the same account, but on my desktop PC, I'd like to only show family contacts AND family rooms in the same filter. The inverse at work.

Grouping contact/rooms with a custom hierarchy (and be able to customize notifications for this) is really a feature I need to have a cooler life with Matrix.

**Comment by t3chguy** [comment]
Given that a room can be in multiple spaces at once, Notifications will not be a per-space setting.

**Comment by SimonBrandner** [comment]
@t3chguy It would be great to have a way to handle per-space notification settings. I think it's a thing that a lot of people expect, no matter what environment they are coming from. 

Although, I am aware that this is hard/impossible to figure out... I just think we should keep in mind that lots of people may want this.

**Comment by t3chguy** [comment]
It is unlikely to be part of the Spaces project, especially as the paused Notifications project is rebuilding everything from 0.

**Comment by SimonBrandner** [comment]
@t3chguy Yeah, I definitely get that. Just let me hope :joy:

**Comment by Extarys** [comment]
Per-space notification could be hard to implement if the same person or room is in multiple spaces with different notification settings. What a headache.

**Comment by MurzNN** [comment]
> @MurzNN Did you use MSN Messenger back in the day? It seems to me that you would prefer to categorize your contacts (and rooms) independently from what _they_ categorize you.

I used to use ICQ, Trillian, Miranda, PSI, and a lot of other old school messengers, and was always glad to personally organize and group list of people and rooms! I even has can rename contacts only on my side!!! And modern Matrix still can't give me the same features yet! That's very sad :-(

> I thought Spaces was more about a _discord_ feeling, To have people grouped together, on both ends.

But did you think that people need to have externally-enforsed grouping of his own list of rooms always in his panel? I don't think so. This can be needed only when searching new rooms/people in some already known community, or exploring new communities (for find and join to new interesting rooms), and that's all, after this users don't need to lookup the community and all its rooms/members.

**Comment by MurzNN** [comment]
> Given that a room can be in multiple spaces at once, Notifications will not be a per-space setting.

But there are many situations, when one room must be in two Spaces, for example shared chat between two distinct communities, or group chat with 2 your personal friends, which also work in same company with you, so you discuss "friends" and "work" topics in this room, and want to see it in both communities, etc.

**Comment by MurzNN** [comment]
Other real life example - I'm the member of 3 communities (in Slack, VK, Telegram, Discord) - JS, Vue, PHP, OSM, Drupal, because I work on project, that contains all of that technologies, but for me interested is only OSM-related part of that communities rooms. Each community have the little list of OSM-related rooms, so I grouped them personally for me into one "OSM" tag, despite that they are from totally different communities.

**Comment by t3chguy** [comment]
As I already said earlier, rooms *CAN* be in multiple spaces. This makes the concept of space-specific notifications very muddled because what if you have the Drupal space set to All Messages but the OSM space which shares some rooms to Mute. Now a room is set to both All Messages & Mute.

**Comment by MurzNN** [comment]
> Per-space notification could be hard to implement if the same person or room is in multiple spaces with different notification settings. What a headache.

Not so hard, just select most noisable notification from available variants of this room.

**Comment by t3chguy** [comment]
That's not adequate for everyone.
Either way, given the scoping, no more discussion about Notifications here, those will be dealt with under the FTUE Notifications project and not Spaces.

**Comment by Extarys** [comment]
> I used to use ICQ, Trillian, Miranda, PSI, and a lot of other old school messengers, and was always glad to personally organize and group list of people and rooms! I even has can rename contacts only on my side!!! And modern Matrix still can't give me the same features yet! That's very sad :-(

Yeah, that is the purpose of categories or folders normally. Like the screenshot I sent. You might be older than me with all those clients :laughing: 

> But did you think that people need to have externally-enforsed grouping of his own list of rooms always in his panel? I don't think so. This can be needed only when searching new rooms/people in some already known community, or exploring new communities (for find and join to new interesting rooms), and that's all, after this users don't need to lookup the community and all its rooms/members.

That is indeed why I think a category function would be nice.

**Comment by MurzNN** [comment]
>> How to add room to space, with keeping it visible in default list of room (in "Home" space)?

> You can't. The Home space lists orphaned rooms, i.e ones which don't have another home.

For solve this problem will be good to have some checkbox "Show rooms from this space in Home space" in per-user Space settings, or something similar.

**Comment by t3chguy** [comment]
You can shift-click to select multiple spaces, so you could select both Home and that Space instead of having two ways to achieve the same behaviour.

**Comment by heyakyra** [comment]
> Split into the following milestones:
> 
>     1. #16203
> 
>     2. #16204
> 
>     3. #16205
> 
>     4. #16206
> 
>     5. #16207
> 
>     6. #16208

Which phase covers #5240 (No way to promote/demote people in a group) and which one covers migration of existing groups/communities to spaces?

**Comment by t3chguy** [comment]
> Which phase covers #5240 and matrix-org/synapse#2855 (No way to promote/demote people in a group)?

https://github.com/vector-im/element-web/issues/16206 - Managing Spaces

> Which phase one covers migration of existing groups/communities to spaces?

None.

**Comment by heyakyra** [comment]
> > Which phase covers #5240 and [matrix-org/synapse#2855](https://github.com/matrix-org/synapse/issues/2855) (No way to promote/demote people in a group)?
> 
> #16206 - Managing Spaces

Thank you!

> > Which phase one covers migration of existing groups/communities to spaces?
> 
> None.

None as in it isn't planned, or as in it will be after all the full implementation? If the former, what will happen to old groups/communities?

**Comment by t3chguy** [comment]
> None as in it isn't planned, or as in it will be after all the full implementation? If the former, what will happen to old groups/communities?

As far as I am aware it isn't planned, due to the large impedance mismatch in features between them.

> what will happen to old groups/communities

Element Web that supports spaces will not be able to view/manage old Groups/Communities

**Comment by jens-pa** [comment]
> > what will happen to old groups/communities
> 
> Element Web that supports spaces will not be able to view/manage old Groups/Communities
WHAT??
Until now I eagerly anticipated the implementation of spaces as a very cool feature. ...but now I have to choose between communitys and spaces? WTF.
Will communitys disappear or will there be totally different networks using one or the other?

**Comment by t3chguy** [comment]
Spaces is a specced replacement for Communities. Communities are centralised and specific to Element + Synapse. Spaces will be in the Matrix spec and available for any Server & Client to implement.

**Comment by MurzNN** [comment]
For solve Community»Space migration problem maybe can be possible to implement some bot, that will automate converting of specific old-school Community to new Space (create same Space, add rooms, invite users, set permissions)?

**Comment by shukon** [comment]
> For solve Community»Space migration (and Tags»Spaces) problem maybe can be possible to implement some bot (or script that works with user credentials), that will automate converting of specific old-school Community to new Space (create new Space with same description like the Community, add rooms, invite users, set permissions)?

For the record, there are https://github.com/t2bot/groups-to-space-bot and https://t2bot.io/spacebot/ which does some of the things you mentioned.

**Comment by DanMan** [comment]
What's the reasoning behind not listing all the rooms inside a Space for everyone in that Space? It seems like even a public room with guest access is not listed for all the Space members.

**Comment by t3chguy** [comment]
Guest Access has nothing to do with whether or not you can see the metadata of a room. 
https://gist.github.com/t3chguy/fdf541446d992d1fc96b8089b342fe7b#why-cant-i-see-some-rooms-in-a-space

**Comment by t3chguy** [comment]
Closing as Spaces has left Labs

**Comment by blaggacao** [comment]
This has come out _very_ nice.

Is there already a feature request for "allowing to silence an entire space for a configurable amount of time (e.g. 2hours or sat/sun or mon-fri 7pm-7am)"?

**Comment by aaronraimist** [comment]
@blaggacao https://github.com/vector-im/element-web/issues/3569

**Comment by blaggacao** [comment]
After looking around for a bit I also found: https://github.com/matrix-org/matrix-spec/issues/881
