### ISSUE TITLE
Matrix Spaces Milestone 3

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#16205]
Private space, full cycle journeys

- [x] Create a private space
  - [x] Naming the space
  - [x] Adding existing rooms
  - [x] Creating new rooms
  - [x] Invite by email
- [x] Joining the space by email invite
- [x] Previewing the space
- [x] Joining it
- [ ] Sanity check personal spaces (private spaces you haven’t invited people to)
