### ISSUE TITLE
Matrix Spaces Milestone 1

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#16203]
Public space, full cycle journeys

- [x] Create a public space
  - [x] Naming the space
  - [x] Adding existing rooms
  - [x] Creating new rooms
  - [x] Share by URL
- [x] Joining the space by URL
- [ ] Previewing the space
- [ ] Joining a space
  - [ ] Auto-joining rooms within the space

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/16490 and https://github.com/vector-im/element-web/issues/16491
