### ISSUE TITLE
Matrix Spaces Milestone 6

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#16208]
Hierarchical Spaces

- [x] Adding subspaces to spaces you can manage
- [x] Switching between subspaces
- [ ] Selecting multiple subspaces
- [x] Managing subspaces
