### ISSUE TITLE
Matrix Spaces Milestone 4

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#16206]
Managing spaces

- [x] Adding existing rooms & creating new rooms within a space
- [x] Inviting new users to the space
- [x] Managing room settings which belong to spaces
- [x] Accessibility 

This milestone is potentially shippable
