### ISSUE TITLE
IA1.3: Discovery: History

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#19528]
<img width="429" alt="Screenshot 2021-11-11 at 17 29 44" src="https://user-images.githubusercontent.com/4626865/141342562-4b4c0c48-c68c-470b-8d0b-a8cf1d89d213.png">

The intent of these changes is to test an alternative interaction to breadcrumbs. This interaction places them in a global place in the hierarchy, reduces avatar fatigue, and builds on affordance from browser histories/other platforms.

- Part of a larger project to [improve our IA](https://github.com/vector-im/element-meta/issues/56).
- [Figma](https://www.figma.com/file/u6xYQamXT4BqUJ5cKnkbWr/iA-Prop?node-id=650%3A142040)
- Merging behind a labs flag, on by default on develop to learn more from lived usage there.

## Tasks
- [x] Replace Explore icon with History icon	
- [x] Show room history on hover	
	Show a list of recently viewed. Capped at 20. Scrollable. Show on hover. If clicked, click off to dismiss.
- [x] Consider adding exploring a space as a history item	
- [x] Legacy housekeeping	
	Remove the settings flag
	Remove magical behaviour of hiding when in <20 rooms
