### ISSUE TITLE
IA1.1: Discovery: Avatars, titles & menus

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#19526]
<img width="442" alt="Screenshot 2021-11-11 at 17 17 40" src="https://user-images.githubusercontent.com/4626865/141340908-41cdaa74-19ab-4d0b-b1fc-8c115fcc461b.png">

The intent of these changes is to re-arrange elements to create a clearer hierarchy of global, per space, and per room actions.

- Part of a larger project to [improve our IA](https://github.com/vector-im/element-meta/issues/56).
- [Figma](https://www.figma.com/file/u6xYQamXT4BqUJ5cKnkbWr/iA-Prop?node-id=607%3A107832)
- Merging to develop to test there, rapidly iterate for production.

## Tasks
- [x] Move user avatar to Space panel. Update to the latest designs. Use existing context menu on click.
- [x] Remove user avatar from message composer. Update to the latest designs. Temporarily move 'Set status' to user context menu for users who have it labs flagged.
- [x] Add room list header for 'Home' or 'Space Name' to room list	
- [x] Move 'Search' to new location in designs. With Explore in lieu of 'History' until we get to 1.3.
- [x] Add existing Space context menus to room list header	
- [x] Add a new [+] menu next to room list header.
   Home: ???
   Space: Start new chat + room. Invite to Space.
- [x] Update existing [+] interactions	
   People: Start new chat. Invite to Space.
   Rooms: Create new room. Add existing room. Explore rooms.
- [x] Sanity check collapsed states after making the above changes

**Comment by turt2live** [comment]
DND can probably just get quietly lost in the migration to greener pastures. It's very much a developer-friendly feature, which means developers can use the Settings Explorer or JS console to trigger it.

For custom status, we might be able to just lose it as a feature - it's backed by a bad implementation and doesn't fit the desired UX at all. Will check internally.

**Comment by frandavid100** [comment]
> The intent of these changes is to re-arrange elements to create a clearer hierarchy of global, per space, and per room actions.

In order to reach that goal, I think it would be better to move the current space's name to the top, like this:

![image](https://user-images.githubusercontent.com/694794/144118991-4570d726-24ad-4a88-8e99-08aedb9b5c5f.png)

That way all three elements (account, space and room) will be at the same level and ordered left to right; in my opinion that would represent action hierarchy much more clearly than the current than the current experimental UI, which shows the space's name almost at the top but not quite.

**Comment by ShadowJonathan** [comment]
@frandavid100 i think you should file a seperate issue for this

**Comment by frandavid100** [comment]
> @frandavid100 i think you should file a seperate issue for this

Thanks for the advice. I just did: https://github.com/vector-im/element-web/issues/20017
