### ISSUE TITLE
IA1.4: Discovery: Preferences

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#19529]
<img width="264" alt="Screenshot 2021-11-11 at 18 38 24" src="https://user-images.githubusercontent.com/4626865/141351441-8db06d8d-feb3-44ad-98a6-dc091b859b3e.png">

The intent of these changes is to provide quick and intuitive preferences to allow committed users to grow into their needs, and set sensible defaults for new users.

As we're also testing the ability to 'pin' dedicated spaces for all favourites, we'll also modify the default favourites behaviour to be per view.

- Part of a larger project to [improve our IA](https://github.com/vector-im/element-meta/issues/56).
- [Figma](https://www.figma.com/file/u6xYQamXT4BqUJ5cKnkbWr/iA-Prop?node-id=648%3A126096)
- Merging behind a labs flag, on by default on develop to learn more from lived usage there.

## Tasks
- [x] Update existing favourites interactions to be per view (Home, per Space)	
- [x] Add user preferences for 	
	Show all favourites in: Home or Space panel
	Show all people in: Home or Space panel
	Show all rooms in Home: By Space or All together
	Hide low priority rooms
- [x] Add per space settings for	
	Show people in this Space
- [x] Add sidebar preferences to existing Settings	
- [x] Update expand/collapse interaction to make way for quick settings (https://github.com/vector-im/element-web/issues/17993)
- [x] Quick settings	
	Refresh user context menu to match latest designs, including 'Quick settings' for pinning spaces for Favourites / People.

**Comment by t3chguy** [comment]
M raised a concern about `All rooms` using the Home icon, he expected it to be something like a Globe

**Comment by ShadowJonathan** [comment]
Concern: That button in the bottom right will look awkward as other spaces will slide under it, it could easily be confused as a space itself with it's look and positioning.

Pic illustrating the effect;

![image](https://user-images.githubusercontent.com/22740616/141837233-69e0878c-e968-4d28-aaf4-0277e4fb0dd7.png)

**Comment by t3chguy** [comment]
@ShadowJonathan do you mean bottom left?

**Comment by ShadowJonathan** [comment]
Whoops, yes, fixed

**Comment by t3chguy** [comment]
The IA project has more buttons planned to be included in the bottom left, e.g notifications & quick settings ftr

**Comment by niquewoodhouse** [comment]
> * [ ]  Add per space settings for
>   Show people in this Space

<img width="600" alt="Space_ preferences@2x" src="https://user-images.githubusercontent.com/1587166/144083617-1445721a-9d7f-4971-bed9-e622de10a8aa.png">

I was wondering if we need to have a save/cancel button interaction, can the form just auto-save itself?

Copy: 
- Sections to show
  - People
    - This groups your ongoing conversations with members of this space.  Turning off will hide it from your view.

**Comment by t3chguy** [comment]
> I was wondering if we need to have a save/cancel button interaction, can the form just auto-save itself?

Whichever you prefer is trivial

**Comment by niquewoodhouse** [comment]
> > I was wondering if we need to have a save/cancel button interaction, can the form just auto-save itself?
> 
> Whichever you prefer is trivial

Thanks, would like to start without the save/cancel buttons then.  We're experimenting so I think it's fine to differentiate here.
