### ISSUE TITLE
IA1.5: Discovery: Spotlight search

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-web#19530]
<img width="918" alt="Screenshot 2021-11-11 at 18 38 48" src="https://user-images.githubusercontent.com/4626865/141351872-6be9c864-a65c-403a-a4a6-f30f3d3a7ae8.png">

In chorus with the other IA changes, we'd like to test Spotlight search.

While it might seem unrelated to fixing the foundational IA, we've repeatedly found that users intuitively reach for the filter box to find anything.

This first implementation won't implement unified search (for messages, file names, people, etc) and instead will just link to perform those actions. If this test is successful, we'll build out towards unified search later.

- Part of a larger project to [improve our IA](https://github.com/vector-im/element-meta/issues/56).
- [Figma](https://www.figma.com/file/u6xYQamXT4BqUJ5cKnkbWr/iA-Prop?node-id=607%3A107832)
- Merging behind a labs flag, on by default on develop to learn more from lived usage there.

## Tasks
- [x] Restylise 'filter' as search in room list		
	Update to the latest designs.	
- [x] Expose keyboard shortcut		
	Update to the latest designs. Show keyboard shortcut on focus and while empty.	
- [x] Best effort spotlight search experience		
	- [x] Show a list of recently viewed rooms.	
		Show a list of non-scrollable rooms when opening the spotlight search experience. Non scrollable.
	- [x] Show a list of recent searches in default open state.	
		Reasonable, non-scrollable, maximum depending on available vertical space. Store locally. Don't worry about syncing cross-client for now. We can add that later, if we learn it's needed.
	- [x] Display search results of rooms you've joined.	
		Clear default states to show search results from rooms you've joined. Show: (1) Avatar (2) Room / DM room name (3) Caption with one of: Space name if room, Matrix ID if user, Room ID if no space. Blank if none.
	- [x] Expose secondary actions with text links in micro copy, or buttons. 	
		While the spotlight experience is 'best effort' to validate all of the Phase I changes, simply link to: Explore rooms, Explore space, message search.
- [x] Sanity check collapsed state.

**Comment by t3chguy** [comment]
> Show a list of non-scrollable rooms when opening the spotlight search experience. Non scrollable.

Not sure how this would behave given that room names are variable so the list of tiles that fit is also variable

> Expose secondary actions with text links in micro copy, or buttons.
While the spotlight experience is 'best effort' to validate all of the Phase I changes, simply link to: Explore rooms, Explore space, message search.

Needs design

> Room ID if no space

I don't think this is a good idea, room IDs are meant to be hidden from users
