### ISSUE TITLE
Release automation: epic

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#19573]
Epic for the Q4 2021 release automation work to allow us to build element with a single command

 * [x] https://github.com/vector-im/element-web/issues/19449
 * [x] https://github.com/vector-im/element-web/issues/19450
 * [x] https://github.com/vector-im/element-web/issues/19570
 * [x] https://github.com/vector-im/element-web/issues/19571
 * [x] https://github.com/vector-im/element-web/issues/19572

**Comment by t3chguy** [comment]
Closing in favour of https://github.com/vector-im/element-web/issues/23538
