### ISSUE TITLE
[Meta-issue] Document supported matrix versions, and introduce compatibility modes for older ones.

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-web#19674]
#### What would you like to do?

- [ ] Document the matrix versions supported (https://github.com/badges/shields/issues/7245)
	- [ ] Document this within the client (for if users are running versions on their own servers)
- [ ] Introduce compatibility probing (call `/versions`)
	- [ ] Show user-facing error when server and client supported versions mismatch 
	   ("Cannot communicate with server, your client supports versions v1.1 and v1.2, but the server only supports v1.0")
- [ ] Introduce compatibility modes based off of the `/versions` response for older versions

#### Why would you like to do it?

Matrix now has a quarterly release cadence, it'd be nice to make element compatible with older matrix versions in a easily understandable way. (So that users may check compatibility for themselves)

### Additional context

Android and iOS versions of this enhancement: https://github.com/vector-im/element-ios/issues/5115, https://github.com/vector-im/element-android/issues/4441

**Comment by ShadowJonathan** [comment]
It might be better to expand that into matrix-js-sdk and such, with matrix versions in mind to merge compatibility for broader things.

I do agree it *is* quite broad, those action items should be individual issues, but i just wanted to throw this in here for now to branch it off later into seperate issues when the need arises. So this is a meta-issue, of sorts.

**Comment by turt2live** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/22346
