### ISSUE TITLE
Amend + context menu in space header

### ISSUE THREAD

**Issue by niquewoodhouse** [vector-im/element-web#20601]
### Your use case

In iA1 testing https://github.com/vector-im/element-web/issues/19706 we've seen people become confused by the current options within the `+` button on a space.

### **Aim**

When a space is selected, the `+` should only show options that directly influence the user's view of that space, and are consistent with other adding experiences in the UI

<img src="https://user-images.githubusercontent.com/1587166/149913526-37f3d801-25e7-491d-b9d8-5d4f70af41df.png" width="600">

### **Tasks**

- [x] Remove start new chat [1]
- [x] Amend explore rooms to direct users to explore 'space home', not open public directory (unless the space is Home or Rooms not in a space)
- [x] Add 'add room' and 'add space' (as seen in right click on space avatar in sidebar (below screenshot)

<img src="https://user-images.githubusercontent.com/1587166/149915006-8a0ca823-9ab5-4db9-8c25-eef149e40c4e.png" width="300">

[1] Would like to see this brought back in the future with a different UX, but there's ongoing discussions around this

### **Mockup** 
![image](https://user-images.githubusercontent.com/1587166/149916647-720f0b15-1cde-4021-bba9-8f8c69cab4f0.png)
