### ISSUE TITLE
Amend drop down menu in Space header

### ISSUE THREAD

**Issue by niquewoodhouse** [vector-im/element-web#20606]
### **Tasks**

- [x] Amend iconography of 'explore rooms' to use same icon as found in `+` context menu
- [x] Add space home to top of list <sup>1</sup>
- [x] Swap all home icons referenced in UI to be the icon found in [Compound](https://www.figma.com/file/X4XTH9iS2KGJ2wFKDqkyed/Compound?node-id=1373%3A13)

<img src="https://user-images.githubusercontent.com/1587166/149927859-5e3215aa-1af9-49f9-bf38-4432fdc92719.png" width="400">

(The current menu in production has an `add` subheading above the + room and + space options, while this mockup has a border.  Lets keep the `add` for now, please ignore this difference).

### **Tasks tbc**

- [ ] Find out if people are visiting space home to get an overview of the space

**Notes**

1 - This was in the original designs, with the intention being to learn if users are looking for an overview of the space, instead of just exploring rooms.  From some testing in https://github.com/vector-im/element-web/issues/19706 we've learned that there is an appetite to get that overview.  Including this link in the menu might let us know more about how large that appetite  is, before we proceed with some potential amends to the space home/explore space views.
