### ISSUE TITLE
IA 2.1: Discovery: Make search experience more powerful

### ISSUE THREAD

**Issue by niquewoodhouse** [vector-im/element-web#20616]
**Intro**

As part of testing IA experiments https://github.com/vector-im/element-web/issues/19706, we've seen an interest from users in the following improvements:

- Using the search to search for messages
- Support for filters (eg "text:in#room-name from:user....")
- Improvements to design (we will address these with a longer term view of what we would like to support in the search)
- Result ordering and structure, including:
  - https://github.com/vector-im/element-web/issues/20559 
  - https://github.com/vector-im/element-web/issues/20769 
  - https://github.com/vector-im/element-web/issues/20635 
  - https://github.com/vector-im/element-web/issues/20634
  - https://github.com/vector-im/element-web/issues/20538
  - Result groupings

**Select user insights**

> “Sometimes search bars have some special things you can do, eg visual code - colon does something, the first character of the search defines what happens”

> “Adding support for message search seems like a nobrainer. Also adding filter support like discord and slack have:
"text" in:#channelname from:user ,...” [Link](https://github.com/matrix-org/element-web-rageshakes/issues/7859)

**Task**

- [x] #21139
- [ ] #21291
- [x] #21352
- [ ] Provide options that enable this
- [ ] Test options in prototypes with cohorts of new and experienced users
- [ ] Identify what else might be helpful to users and why (eg search files)
