### ISSUE TITLE
Amend quick settings

### ISSUE THREAD

**Issue by niquewoodhouse** [vector-im/element-web#20623]
Small amends to quick settings based on testing iA https://github.com/vector-im/element-meta/issues/56 

**Tasks**

- [ ] Amend theme picker to be easier to switch between the two options (we don't seem to be anywhere near having more themes, so....why not make it a bit easier as it's supposed to be quick to use settings)<sup>1</sup>

https://user-images.githubusercontent.com/1587166/149988708-ef00fd4e-cc88-4f37-9e8b-4132108970f0.mp4

**Future tasks we might consider worth doing**

- [ ] Clarify if theme picker should remain in user menu also
- [ ] Discover if there are other settings a user might want quick access to, or if none, discuss amending title to not be 'quick settings'

**Notes**

<sup>1</sup> I've put the designs [here](https://www.figma.com/file/NhIspIv14PatTKhVUZ4ldC/Milestones-1?node-id=545%3A56490). I think there might already be something like this in screensharing in video call, but not sure.  @t3chguy I'd like to personally go with the alternative option (which doesn't use accent colour), but I leave it with @nadonomy to review.

**Comment by t3chguy** [comment]
Ftr we do also have high contrast and deployments can have more themes defined via config.json and users can add custom themes via labs

**Comment by niquewoodhouse** [comment]
> Ftr we do also have high contrast and deployments can have more themes defined via config.json and users can add custom themes via labs. @niquewoodhouse does this impact this design at all?

Yes,  I think it negatively impacts it - I think the above picker makes sense for two themes but not if there's more than 3.

**Comment by kittykat** [comment]
@niquewoodhouse what do we want to do here? Close the issue as we can have more themes? Or show different UIs based on number of themes?

@t3chguy what does the theme switcher in the user menu at the top do when a user has 3 themes?

**Comment by t3chguy** [comment]
> @t3chguy what does the theme switcher in the user menu at the top do when a user has 3 themes?

Breaks, always just toggles between Light & Dark, ignoring the default set via config.json

**Comment by kittykat** [comment]
I'm going to close as this works as expected
