### ISSUE TITLE
IA 2.1: Build: Make search experience more powerful

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#21121]
Issue to track research and building Phase II IA improvements

## Tasks

- [x] [Add join room button if you're not in the room which is showing in search results](https://github.com/matrix-org/matrix-react-sdk/pull/7830)
- [x] https://github.com/vector-im/element-web/issues/21136
- [x] #21285
- [x] #21354
- [x] #22361
- [x] #22589
- [x] #22554
- [x] #22553
- [x] Will be closed as part of this issue:
  - [x] #19349

### Resources
- [Figma](https://www.figma.com/file/X7PvFE7f73mI7pJ9WLM61l/%5BWeb%5D-%5BSearch%5D?node-id=356%3A22420)

### Stretch goal
- [ ] Investigate what is involved in searching public spaces alongside rooms
- [ ] Results, ordering and structure
  - [x] #21341
  - [x] #21641
  - [ ] To consider:
    - #21710
- [ ] Fuzzy search
  - [ ] Test harness for fuzzy search
  - [ ] #21640
  - [ ] Propose initial criteria for fuzzy search
  - [ ] Will be closed as part of this issue:
    - [ ] #14410

**Comment by kittykat** [comment]
I need to write up next steps before this issue should be closed, so removing other assignees now
