### ISSUE TITLE
Survey users with proposals for search experience result ordering improvements

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#21139]
### Tasks

- [x] Review feedback and pull out common themes for requested result ordering (@kittykat )
- [x] Review approach other products take
- [x] Create proposals for potential improvements (@niquewoodhouse )
- [x] Survey users to get confidence on proposals (@niquewoodhouse )

Michael to support Kat and Nique with reviews and technical expertise

### Feedback conclusions

Feedback submitted through the app and in issues was aggregated and split by type of ordering that users are asking for.

#### Most important

* Give preference to perfect string matches (e.g. search for "IT" should rank room named "Internal IT" over "Nit Pick")
* Prioritise rooms with recent activity
* Prioritise matching on room name and display name:
  1. Room name and display name (if set, otherwise consider alias or MXID as equivalent)
  2. alias and MXID / Space name that the room/DM is in
 
Challenges: need to work out when e.g, `#internal-it:example.com` should result in a higher search result than "Nit Pick"

#### Clear benefits

* Show notification counts next to rooms: some users wanted to have rooms with unread messages prioritised in the search results

#### Considered

* Change how results are grouped
* Prioritising results from current space: we need to have a better understanding if users are space aware when they are filtering

#### Spaces behaviour

* If the selected result is from another space, switch to home if "Show All Rooms" is selected. TBD how to handle if "Show All Rooms" is not selected

Limitations:
 * We cannot track frequency of visit to room or spaces cross-device
 * We could add code to track it per session per device
 * We can track recently visited (currently used in breadcrumbs)

### User survey

1. Ask users to order by preference
  * Perfect match for search term (e.g. searching for "it" returns "IT support" before "Nit pick")
  * Recently activity in room (this includes, room creation, title/avatar/topic updates, joins/leaves and messages) 
  * Recent message activity in room
  * Has unread messages
  * Has pings (red notifications) for you
  * How often you've visited this room recently (limited to this session and device)
  * Most recently visited (results which are in breadcrumbs are prioritised)
  * Show results which are in the current Space first
  
  Please explain why this is your preferred ordering

2. Is there anything else you would like to be prioritised? Where would it be in the priority?
3. Do you use the breadcrumbs in the search dialog?
4. [2-3 different gifs]
  How would you rate this flow and why?

**Comment by t3chguy** [comment]
> If the selected result is from another space, switch to home if "Show All Rooms" is selected. TBD how to handle if "Show All Rooms" is not selected

This isn't really related to Spotlight, the behaviour should match regardless of how you switch rooms, e.g if you click a permalink in a room timeline. Currently it does the following

+ Choose canonical parent space if one is known and joined
+ Find a real root space containing this room
+ Find a metaspace containing this room (going top to bottom)
+ If all else fails (basically impossible) pick the first space (Home/All rooms)
