### ISSUE TITLE
⭐️ Upgrade to React 18 ⚛️

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#21594]
## Why?

We’re stuck on React 17 and due to the required migration to react-testing-library and other things can’t update to React 18 (released March ‘22). This prevents us from benefiting from the latest fixes and improvements in the framework.

Reference: https://reactjs.org/blog/2022/03/29/react-v18.html https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html

## What?

We’ll carry out all the required migration steps and update to the latest version of React.

## Plan

```[tasklist]
### Tasks
- [x] https://github.com/matrix-org/matrix-react-sdk/pull/10255
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/10313
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/10312
- [ ] https://github.com/vector-im/element-web/pull/24766
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/10311
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/10314
- [ ] Switch to new render API
- [ ] Enable Strict mode
```

## Internal references

myhours: https://app.myhours.com/#/projects/2028428/overview

**Comment by SimonBrandner** [comment]
> @gsouquet @RiotRobot Can I work on this ?

I've assigned you to the issue. If you need any help/have any questions be sure to visit [#element-dev:matrix.org](https://matrix.to/#/#element-dev:matrix.org)!

**Comment by TheReshma** [comment]
Hi @gsouquet , I couldn't find this file `RoomSettings-test.js` . Has it been renamed/deleted lately? Thanks.

**Comment by gsouquet** [comment]
React 18 is now fully released and available on npm https://reactjs.org/blog/2022/03/29/react-v18.html

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-react-sdk/pull/10311#issuecomment-1466199044 has the latest news
