### ISSUE TITLE
Reduce time required to run tests

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-web#21971]
## Why?

Running the full test suite can take up to the order of minutes to complete which negatively impacts our productivity.

## What?

We’ll gather performance metrics on test execution time to define and attack reasonable performance goals.

## Plan

```[tasklist]
### Tasks
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/9599
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/9938
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/10124
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/10255 
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/10124
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/10435
```

- Added a slow reporter which is running on develop
- Removing enzyme in profit of react-testing-library will also improve the execution time
- Muting the console output didn't improve the execution in this PR https://github.com/matrix-org/matrix-react-sdk/pull/9938

## Internal references

myhours: https://app.myhours.com/#/projects/2028404/overview
