### ISSUE TITLE
The Welcome Checklist: Iteration & Experiment 1  (Mini-Epic)

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#22463]
We're building a new landing page for users when they get to Element [see Epic issue](https://github.com/vector-im/element-web/issues/21947). This issue discusses the first iteration of this new page and the things we're looking to learn.

### Hypothesis
We believe that by having one hero action where the user gets a reward and immediate feedback, followed by a series of investment tasks we kick start the first "retention loop" and therefore increase D1. This also will allow us to give users a tailored experience of element, based on what we know about them.

As this is a hypothesis, we've taken the ideal state and broken it into chunks that can be delivered over time:

**This is Delivery 1**
Which focusses on:
- Asking the use case question
- Getting baseline metrics for the one hero action
- Understand if the checklist "works"
- Provide a way back to the 'Welcome Home' screen

| Task | Notes | Learning | Measure | 
|---|---|---|---|
| **Add a use case screen** | So we can learn more about our users. This screen can be answered or skipped. It appears before the user gets to Element product and after account Creation. Users signing in do not see this screen. This screen is only seen once. | What is the most popular use case? What tasks do those user groups complete in product to be successful (or not successful)? | UserProperties > ftueUseCaseSelection > PersonalMessaging ("Friends and family") , WorkMessaging (Teams) , CommunityMessaging (Communities) , Skip |
|  **Hero image _action_: Send first message** | For now we want all 3 user groups to have the same hero action. It sets a baseline and allows us to see if this solution is successful in principle | Do users click on the hero action? <br /> Do users complete the hero action? <br /> Does it make user's stickier? <br /> Does the success (or failure) of the hero action differ based on user group? | Need an action trigger for this button (maybe a property on an already existing event? |
| **Checklist: With the first 3 _investment_ options; Enable notifications, Download Element, Set a profile picture** | This checklist is currently "dumb". Nothing can be dismissed, nothing changes based on the user group or user input. We want to understand if giving user "Investment" actions works to kick-start the retention loop | Are items started? Are items finished? Does a started or finished item impact D1? | All buttons would need an event (or property on existing event) so we can see start and successful completion of each action | 
| **Add a way to get back to the welcome home screen** | Something quick and easy in the left nav that guides users back to the Welcome Home screen | Does the ability to get back to this screen engage users? | Event on the left-bar button and it's [x] to see if users are more likely to click or hide the button | 

### Questions to answer
| Question | Answer | 
|--|--|
| What happens when all the items are checked off? | One day the checklist will show more items, for the first iteration show all the actions as completed and the Feedback box |
| What happens if the user is signing in, or is not a new to element user, what does this screen look like? | We will show this screen to new users only. (Temporarily) | 

### Things to do
- [x] Create the use case screen & Ensure the analytics on the use case screen match the mobile ones > UserProperties > ftueUseCaseSelection > PersonalMessaging ("Friends and family") | WorkMessaging (Teams) | CommunityMessaging (Communities) | Skip
- [ ] Create the left bar button that allows users to return to this screen
- [ ] Create the Hero banner, image, and button that translates & scales well. In the first iteration this button will be the same for all user groups (this may change in the future but we want to collect data first)
- [ ] Create a "dumb" checklist with: Create Account (checked off already), Notifications, Download Element, and Set up your profile. These are our first choices but we intend to grow this checklist over time. 
- [ ] Create "Submit Feedback" pane for when the checklist is complete

*Note, all checklist elements have animations too. We need to ensure we can measure all these elements.

## Other
Related to https://github.com/vector-im/element-web/issues/21947

**Comment by daniellekirkwood** [comment]
[Checklist idea generation with the design team](https://docs.google.com/document/d/1d36Op8AHH1emrCfFtx5OJ98ZR2n7sS7yLDvloi8GwzA/edit)

**Comment by niquewoodhouse** [comment]
> - [ ] Checklist: With the first 3 investment options; Enable notifications, Download Element, Set a profile picture

Examples of how checklist could function.  

https://user-images.githubusercontent.com/1587166/172642799-c8add0cc-e059-4c00-9460-632ffccba3e3.mov

> One day the checklist will show more items, for the first iteration we'll ... show other actions?

I think we should show congrats in some way and other a way to send feedback for first iteration:

<img width="1440" alt="completed all steps@2x" src="https://user-images.githubusercontent.com/1587166/172643129-a2f634f9-3d73-4d70-b068-5a8ea6abb640.png">

**Comment by daniellekirkwood** [comment]
Analytics issue: https://github.com/vector-im/element-web/issues/22880

**Comment by niquewoodhouse** [comment]
@justjanne @daniellekirkwood here's an idea of the public profile step:

https://user-images.githubusercontent.com/1587166/179772922-ebf22bb9-dc35-4816-bcd0-f6c68f8e32bd.mov

**Comment by justjanne** [comment]
> @justjanne @daniellekirkwood here's an idea of the public profile step:
> ele-web-onboard-id-server-01.mov

We shouldn’t ever use a checkbox with the behavior of a radio box, if possible. Is there a reason to deviate from this paradigm?

**Comment by justjanne** [comment]
Ah okay. In general I like the flow, though the specifics obviously still have to be ironed out.

**Comment by daniellekirkwood** [comment]
PostHog dashboard: https://posthog.hss.element.io/dashboard/721
