### ISSUE TITLE
Analytics for the Onboarding Checklist 

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#22880]
We are launching an onboarding checklist to provide a focus for new users allowing them to realise the value of the app faster (and hopefully improve D1 retention). The first release of the checklist is to set a baseline against our current experience. 

[The new designs can be found here](https://www.figma.com/file/ZDVvKC8odsa5Jeml9gCuLd/Web%3A-New-User's-Journey?node-id=1085%3A61418)

**In order to know if we're successful we need to measure a few things:** 

To measure the success of the page (and user's appetite for a checklist we need to better understand the Welcome box in the Room list:
- [ ] [How many people click [x] from the Room list to dismiss it](https://posthog.hss.element.io/insights/5fw6MgIE)
- [ ] [How many people click the Welcome box to go to the Checklist](https://posthog.hss.element.io/insights/5fw6MgIE)

To understand the success of the hero action we need to understand who clicks on the start button, by use case, and who completes the action:
- [ ] [Clicks on the green action button](https://posthog.hss.element.io/insights/XTmQPcuR) (start chat, find co-workers, find your people, start chat). Could be "DM created with a property of from checklist hero action" rather than a brand new interaction event - however fits the current analytics approach. [Graph for Hero click thru composer by use case](https://posthog.hss.element.io/insights/JAXNXGJj)
- [ ] Task complete (we may already track this in posthog) 
- [ ] All filterable by use case (we may already have this ability in posthog)

To understand the success of the checklist items and investment activities we should measure clicks and task completion:
- [ ] [Each item on the checklist should have an event](https://posthog.hss.element.io/insights/J2UTtvNg) (could be a checklist event with a property of which action)... etc.

In order to know that we have improved the experience against the previous version we need: 
* Is task completion higher?
* Is D1 higher?
* Do people use it - or are they using the other access points to the same tasks?
* Once the checklist item is complete - are users able to find the long-term way of doing the action (or are they using the checklist over and over)

**Comment by daniellekirkwood** [comment]
@justjanne  & @niquewoodhouse I'm building out this analytics issue - please let me know if you think it's missing anything or if you'd like to discuss implementation details

**Comment by daniellekirkwood** [comment]
@justjanne I think we discussed all the analytics events needed for this issue? Do you have a list of them, or a common word that could be used to search the [events page](https://matrix-org.github.io/matrix-analytics-events/)?

I think that means your work on this issue is complete, if so, please assign it back to me as I will use it as the issue to create and post links to PostHog tables/graphs

**Comment by justjanne** [comment]
@daniellekirkwood: These should be all relevant events:

* Interaction
  * WebRoomListUserOnboardingButton
  * WebRoomListUserOnboardingIgnoreButton
  * WebUserOnboardingHeaderSendDm
  * WebUserOnboardingTaskSendDm
  * WebUserOnboardingTaskDownloadApps
  * WebUserOnboardingTaskSetupProfile
  * WebUserOnboardingTaskEnableNotifications
* PermissionChanged
  * Notification

**Comment by daniellekirkwood** [comment]
dashboard is here: https://posthog.hss.element.io/dashboard/721

closing
