### ISSUE TITLE
Epic: Test our large components

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#23526]
Q4 (extended quarter) target.

* [ ] Reduce flakiness of tests to <5% (arbitrary goal)
* [ ] Provide guidance on how to write tests which aren't flaky
* [ ] Write tests & refactor as needed `MatrixChat`
* [ ] Write tests & refactor as needed `LoggedInView`
* [ ] Write tests & refactor as needed `ScrollPanel` (and friends)
* [ ] Write tests & refactor as needed `RoomView`

**Comment by paboum** [comment]
It seems like everybody in the team is too busy with fixing bugs to take a look into this or at least assign, estimate, or split this task.
![image](https://user-images.githubusercontent.com/54635274/224134654-5b549378-0314-4da4-80f7-a96ad3c08237.png)
