### ISSUE TITLE
Address chronic scroll issues

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#23541]
Blocked by https://github.com/vector-im/element-web/issues/23540

* [ ] [Stuck in scroll loop](https://github.com/vector-im/element-web/issues/23208#top)
* [ ] [Clicking on a permalink often ends up with the permalink being scrolled off the screen](https://github.com/vector-im/element-web/issues/23393#top)
* [ ] ["Jump to first unread message" / Read Marker is really annoying](https://github.com/vector-im/element-web/issues/4134#top)
* [ ] [Improving jumps on timeline pagination/scrolling](https://github.com/vector-im/element-web/issues/8565#top)
* [ ] [Ability to scrollback can get stuck](https://github.com/vector-im/element-web/issues/18325#top)

**Comment by Johennes** [comment]
Rolling this into https://github.com/vector-im/element-web/issues/23539
