### ISSUE TITLE
Strictify on all layers

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#23542]
## Why?

The non-strict aspects of TypeScript allow for a lot of flexibility but also make it easy for errors to slip in, e.g. when there is no strong contract on null-ness.

## What?

We’ll fix all existing strict-mode violations and enable all strict-mode checks to run on PRs. This will allow us to eliminate entire classes of errors through static code analysis.

Reference: https://www.typescriptlang.org/tsconfig#strict

## Plan

```[tasklist]
### matrix-js-sdk
- [x] Enable `strict` in matrix-js-sdk
```

```[tasklist]
### matrix-react-sdk
- [x] Enable `noImplicitThis` in matrix-react-sdk
- [x] Enable `strictBindCallApply` in matrix-react-sdk
- [x] Enable `alwaysStrict` in matrix-react-sdk
- [ ] https://github.com/vector-im/element-web/issues/21968
- [ ] https://github.com/vector-im/element-web/issues/21967
- [x] Enable `strictFunctionTypes` in matrix-react-sdk
- [x] Enable `strictPropertyInitialization` in matrix-react-sdk
- [x] Enable `useUnknownInCatchVariables` in matrix-react-sdk
- [x] Enable `noUnusedLocals` in matrix-react-sdk
- [x] Enable `strict` in matrix-react-sdk
```

```[tasklist]
### element-web
- [x] Enable `noImplicitThis` in element-web
- [x] Enable `strictBindCallApply` in element-web
- [x] Enable `alwaysStrict` in element-web
- [x] Enable `noImplicitAny` in element-web
- [x] Enable `strictNullChecks` in element-web
- [x] Enable `strictFunctionTypes` in element-web
- [x] Enable `strictPropertyInitialization` in element-web
- [x] Enable `useUnknownInCatchVariables` in element-web
- [x] Enable `noUnusedLocals` in element-web
- [x] Enable `strict` in element-web
```

```[tasklist]
### element-desktop
- [x] Enable `strict` in element-desktop
```

**Comment by Johennes** [comment]
@t3chguy did a quick pulse-check of what's left in matrix-react-sdk right now:

| Strict attribute | Errors | Files |
|-|-|-|
| useUnknownInCatchVariabls | 151 | 64 |
| strictFunctionTypes | 102 | 57 |
| strictNullChecks | 4749 | 699 |
| strictPropertyInitialization | 167 | ~20 |

Note that `strictPropertyInitialization` cannot be enabled until `strictNullChecks` is enabled.

**Comment by t3chguy** [comment]
`noImplicitAny` cannot be enabled until `strictNullChecks` either in our case due to some of the js-sdk relying on the strict parser for implicit typing

**Comment by t3chguy** [comment]
I am making good progress with `strictNullChecks` - down to 3814 errors in 555 files

**Comment by paboum** [comment]
> The non-strict aspects of TypeScript allow for a lot of flexibility but also make it easy for errors to slip in, e.g. when there is no strong contract on null-ness.

I never understood the so called "front end" programming, but it seems to me this is basically removal of https://en.wikipedia.org/wiki/Undefined_behavior and, as such, a technical debt. It is somewhat interesting how new generations of programmers believe they can "solve" the issues of having to controlling the flow by selectively ignoring it, but luckily, everyone learns it is unavoidable sooner or later.

Though I cannot contribute here due to lack of js/ts expertise, I would like to cheer @t3chguy up, if you find any errors that cannot simply be solved by single line edits, you will probably be able to isolate meaningful bug reports for others to resolve, or even find specification omissions that will impact other projects. It's better if you do it, not the users filing bug reports, so your effort matters.
