### ISSUE TITLE
Cloud packaging

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#24263]
Goal: Move Element Desktop packaging into Github Actions

- [x] [Build, Sign & Notarise macOS builds](https://github.com/vector-im/element-desktop/pull/486)
- [x] [Build & EV Sign Windows builds](https://github.com/vector-im/element-desktop/pull/517)
- [x] [Build Linux builds and include in a signed debian repository](https://github.com/vector-im/element-desktop/pull/527)
- [x] [Move reprepro task into its own job and protect database via concurrency](https://github.com/vector-im/element-desktop/pull/555)
- [x] Test the above on packages-element-io.element.io
	- [x] Linux updates
	- [x] macOS updates
	- [x] Windows updates
	- [x] R2 file structure
- [x] [Add tests](https://github.com/vector-im/element-desktop/pull/559)
    - [x] Assert macOS package is signed and notarised
    - [x] Assert Windows installer is EV signed
    - [x] Assert apt is happy with debian repo
- [x] [Switch packages over to R2](https://github.com/vector-im/sre-internal/issues/2034)
- [x] [Fix deb changelogs](https://github.com/vector-im/element-web/issues/4879)
- [x] [Keyring package and update gpg keys](https://github.com/vector-im/element-web/issues/23786)
	- [x] [Keyring package](https://github.com/vector-im/element-desktop/pull/565)
	- [x] Deploy keyring package
	- [x] [Recommend keyring from desktop & nightly debs](https://github.com/vector-im/element-desktop/pull/566)
	- [x] Update public gpg keyring with extended expiry
	- [x] ~Update reprepro config~
	- [x] Update keyring package
	- [x] Run release with new keys & test it works
- [x] [Switch to final SSL.com credentials](https://github.com/vector-im/element-desktop/pull/585)
    - [x] Enable CI to assert valid signature
    - [x] Re-test Windows updates
- [x] RETEST EVERYTHING
	- [x] Windows
	- [x] Linux
	- [x] macOS
- [x] Switch from athena + mac mini to the above
    - [x] Stop mac mini operation
    - [x] Sync mac mini's reprepro database
    - [x] [Switch workflows over to live r2 bucket](https://github.com/vector-im/element-desktop/pull/588)
- [x] [Remove afterSign and winSign scripts](https://github.com/vector-im/element-desktop/pull/586)
- [x] ~[ARM64 builds](https://github.com/vector-im/element-web/issues/17942)~
- [x] Update documentation
- [x] Wipe Mac Mini
- [x] Return Mac Mini to the office
- [x] #24907

### Internal references

myhours: https://app.myhours.com/#/projects/1994679/overview

**Comment by t3chguy** [comment]
Decomission blocked for now to keep a revert plan
