### ISSUE TITLE
Wrap up favourite messages

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-web#24261]
- [ ] Change FavouriteMessagesStore to be available via context instead of a global singleton ([ref](https://github.com/matrix-org/matrix-react-sdk/pull/9719#discussion_r1082359510))
- [ ] Adjust FavouriteMessagesView title to match other room titles ([ref](https://github.com/matrix-org/matrix-react-sdk/pull/9719#issuecomment-1398226362))
- [ ] Persist listeners array so it's not cleared every render ([ref](https://github.com/matrix-org/matrix-react-sdk/pull/9719#discussion_r1082352563))
- [ ] Clarify [Florian's comment 1](https://github.com/matrix-org/matrix-react-sdk/pull/9719#discussion_r1082351266) and [Florian's comment 2](https://github.com/matrix-org/matrix-react-sdk/pull/9719#discussion_r1082345488) on use of `forceRefresh` and listener registration and implement
- [ ] Filter nulls from events array in FavouriteMessagesView without typecasting ([ref](https://github.com/matrix-org/matrix-react-sdk/pull/9719#discussion_r1082349124))
- [ ] Fix minor [code review comments](https://github.com/matrix-org/matrix-react-sdk/pull/9719) (e.g. naming of interfaces, TS errors, use named exports, missing string translations, unused context variable, copyright dates, CSS variable usage, clean-up suggestions, svg tweaks, CSS z-index)
- [ ] Investigate use of `useSettingValue` in FavouriteMessageTile ([ref](https://github.com/matrix-org/matrix-react-sdk/pull/9719#discussion_r1082325534))
- [ ] Replace use of mask with direct SVG use ([ref](https://github.com/matrix-org/matrix-react-sdk/pull/9719#discussion_r1082315804))
- [ ] Adjust implementation to match [MSC2437](https://github.com/matrix-org/matrix-spec-proposals/pull/2437). Also propose changes to the MSC to store the data in Account Data instead of Room Account Data. Assuming we continue to believe this is correct, implement based on Account Data.
- [ ] [Fix UI bugs](https://github.com/matrix-org/matrix-react-sdk/pull/9719#issuecomment-1398169811):
    - [ ] Fix "Room search with unexpected result, when hitting random keys on the keyboard."
    - [ ] Fix "It would be nice if the search field can get the focus if you click the search icon"
    - [ ] Fix "Ctrl + F (enabled in options) doesn't trigger search in the favourites view."
    - [ ] Fix "If you favourite a thread root, the thread summary is shown in favourites. But clicking it does nothing."
    - [ ] Fix "The room separation in the favourite view could be improved."
    - [ ] Fix "You cannot jump to the room message, if you favourite an image, voice message or location share (click the message in the favourites view)."
    - [ ] Fix "If you favourite a poll, it explodes with:"

Latest PR: https://github.com/matrix-org/matrix-react-sdk/pull/9719

**Comment by t3chguy** [comment]
https://github.com/vector-im/element-web/issues/25555 points out how confusing this is as it stands. @Johennes can we rip it out until we have time to make it do *SOMETHING*?

Even the docs don't say it does nothing beyond add a button which does nothing to your room list: https://github.com/vector-im/element-web/blob/develop/docs/labs.md#favourite-messages-feature_favourite_messages-in-development

**Comment by Johennes** [comment]
Closing this as the code has been removed and we're not planning to return to it in the imminent future.
