### ISSUE TITLE
Epic: Support Gitter sunsetting

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-web#24262]
### Implement [MSC3946](https://github.com/matrix-org/matrix-spec-proposals/pull/3946) in matrix-js-sdk:

```[tasklist]
### Tasks
- [x] Tests for getVisibleRooms https://github.com/matrix-org/matrix-js-sdk/pull/3038
- [x] Factor out a function to find a room predecessor https://github.com/matrix-org/matrix-js-sdk/pull/3039
- [x] Tests for getRoomUpgradeHistory https://github.com/matrix-org/matrix-js-sdk/pull/3088
- [x] Fix the bug in getRoomUpgradeHistory (tests are cool) https://github.com/matrix-org/matrix-js-sdk/pull/3089
- [x] Refactor to use the new function for finding predecessors https://github.com/matrix-org/matrix-js-sdk/pull/3090
- [x] Adapt getVisibleRooms and getRoomUpgradeHistory to allow using predecessor events when enabled https://github.com/matrix-org/matrix-js-sdk/pull/3042
- [x] Add to the API the ability to get the tombstone event ID as well as the room predecessor ID (rename it findPredecessor) https://github.com/matrix-org/matrix-js-sdk/pull/3095
```

### Implement [MSC3946](https://github.com/matrix-org/matrix-spec-proposals/pull/3946) in matrix-react-

```[tasklist]
### Tasks
- [x] vector-im/element-web#24322
- [x] ⭐ vector-im/element-web#24323
- [x] vector-im/element-web#24324
- [x] ⭐ vector-im/element-web#24325
- [x] vector-im/element-web#24326
- [x] vector-im/element-web#24327
- [x] vector-im/element-web#24328
```

### Other

```[tasklist]
### Tasks
- [ ] https://github.com/Lou82/funnel-/issues/136
- [ ] https://github.com/github/docs-internal/pull/27185
- [ ] https://github.com/snyk-platformcore/enonic-app-auth0-idprovider/pull/11
- [ ] https://github.com/nethopper2/mynethopper-firebase/pull/25
```

De-scoped for now:

- https://github.com/vector-im/element-web/issues/24513
- https://github.com/vector-im/element-meta/issues/1339
- To support accessing Gitter upload content in `<img src="files.gitter.im/...">`, https://github.com/vector-im/element-web/issues/4044

### Internal references

myhours: https://app.myhours.com/#/projects/1994529/overview

**Comment by Johennes** [comment]
Descoping https://github.com/vector-im/element-web/issues/24513 as it's fairly low impact.

**Comment by Johennes** [comment]
Also descoping https://github.com/vector-im/element-web/issues/24420 since there is no clear general solution available right now and we have the general performance improvement of https://github.com/vector-im/element-web/issues/24480 in scope.
