### ISSUE TITLE
Update the copy and visuals for the Account Settings: Notifications page

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#24567]
```[tasklist]
### Tasks
- [ ] Update and change the wording of the toggles in Notifications (top section). Most of the toggles stay the same action, some are moved to a different section.
- [ ] Change Global section to have a new heading and subtext copy
- [ ] Create default radio buttons in the "global' section which maps to current global options. We're removing "Noisy" as that will be replaced by Sound.
- [ ] Play a sound for (noisy checkboxes) section - adding call invitation from the previous "Other" section
- [ ] "Other" as a section to be checkboxes instead of radio buttons
- [ ] Mentions and Keywords: Remove Noisy update Visuals and copy
- [ ] Create email section & add emails that are available as checkboxes
- [ ] "Mark as unread" change visuals and copy to "Clear notifications"
- [ ] Reset to defaults: Introduce button (if possible)
- [ ] Add a banner to the top to tell existing users that their settings have changed
- [ ] Where an existing user has settings that do not map to this new layout, add "Custom" radio buttons. Once the user moves away from 'custom' it is no longer available to select. If the user changes their settings on a different client or device, 'custom' would appear if those new settings do not map to these new global settings
```

[Figma file is here](https://www.figma.com/file/M15i7l4PSPY1B5M7Zhu80H/Notifications?node-id=9040-138235&t=0em9froaUZyQk6lA-0)
![Web](https://user-images.githubusercontent.com/89144281/231733172-81d3aff9-86c2-48ab-b032-ad3a7b0be2cd.png)

**Comment by daniellekirkwood** [comment]
@justjanne : Updated the task list here based on the new changes to the design. Let me know if there's any questions

**Comment by kerryarchibald** [comment]
@justjanne What is your approach for `Notify when someone mentions using @DisplayName or @mxid` when `.m.rule.contains_display_name`, `.m.rule.contains_user_name` have different actions?
Asking because for intentional mentions rollout these rules will be kept in sync with new intentional mentions rules, but I'm not sure what to do when they are out of sync (from another client)

**Comment by justjanne** [comment]
@kerryarchibald So, my current approach is to have an internal model for the notifications page and a way to map to and from it.

When loading the notifications page, I map from the push rules to the internal model, and back to the push rules.

If this doesn't result in the same actions as the current existing push rules, I show the "your push rules have been modified by a different or old client, if you edit them in element you may lose some custom settings" banner.
