### ISSUE TITLE
2023 chapter menu

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-web#24660]
2022 strategy: https://github.com/vector-im/element-meta/issues/246

> The chapter menu is a list of delicious nibbles that members of the chapter can choose at their own convenience in exchange for their 10% chapter time budget
>
> *-- [WAT – Chapter 10% menu 2023 🍽️ – Draft](https://docs.google.com/document/d/1vA5FTdP7gctHlmkZ9S5bDmhebBVZjbZ7BXKnlB2M96w/edit#bookmark=id.y19o0ydtejz9)*

```[tasklist]
### Reduce regressions
- [ ] https://github.com/vector-im/element-web/issues/23542
- [ ] https://github.com/vector-im/element-web/issues/23526
- [ ] https://github.com/vector-im/element-web/issues/24691
```

```[tasklist]
### Developer experience
- [ ] https://github.com/vector-im/element-web/issues/23543
- [ ] https://github.com/vector-im/element-web/issues/21971
- [ ] https://github.com/vector-im/element-web/issues/21970
- [ ] https://github.com/vector-im/element-web/issues/24702
```

```[tasklist]
### Technical debt
- [ ] https://github.com/vector-im/element-web/issues/21594
- [ ] https://github.com/vector-im/element-web/issues/24703
- [ ] https://github.com/vector-im/element-web/issues/14672
```

**Comment by Johennes** [comment]
Closing this off for 2023 since the chapter effectively is the WAT right now. We'll handle further tech debt via the regular WAT roadmap.
