### ISSUE TITLE
Element R: support for Key backup

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#24828]
Depends on https://github.com/vector-im/element-web/issues/25315

https://docs.google.com/document/d/18LuSmlaoeZpsOsiPKIdAxKYsbr9V1etMAYm2vxMId7A/edit#heading=h.wf09j8nuwlov

 * [x] https://github.com/vector-im/crypto-internal/issues/87
 * [x] https://github.com/vector-im/crypto-internal/issues/100
 * [x] https://github.com/vector-im/crypto-internal/issues/101
 * [x] https://github.com/vector-im/crypto-internal/issues/102
 * [x] https://github.com/vector-im/crypto-internal/issues/103
 * [x] https://github.com/vector-im/crypto-internal/issues/104
 * [x] https://github.com/vector-im/crypto-internal/issues/105
 * [x] https://github.com/vector-im/crypto-internal/issues/106
 * [x] https://github.com/vector-im/crypto-internal/issues/107
 * [x] https://github.com/vector-im/crypto-internal/issues/108
 * [x] https://github.com/vector-im/crypto-internal/issues/109
 * [x] https://github.com/vector-im/crypto-internal/issues/110
 * [x] https://github.com/vector-im/crypto-internal/issues/111
 * [x] https://github.com/vector-im/crypto-internal/issues/112
 * [x] https://github.com/vector-im/crypto-internal/issues/113
 * [x] https://github.com/vector-im/crypto-internal/issues/114
 * [x] https://github.com/vector-im/crypto-internal/issues/115
 * [x] https://github.com/vector-im/crypto-internal/issues/155
 * [x] https://github.com/vector-im/element-web/issues/26259

**Comment by richvdh** [comment]
Basic support for key backup is done, though there remain a couple of bugs (eg https://github.com/vector-im/element-web/issues/26316).
