### ISSUE TITLE
Element-R: implement device verification and cross-signing

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#24979]
There are a few aspects to this.

```[tasklist]
- [x] #24982
- [ ] #24833
- [ ] #25092
- [ ] #25093
- [ ] #25314
- [ ] #24983
- [ ] https://github.com/vector-im/element-web/issues/25316
- [ ] https://github.com/vector-im/element-web/issues/25319
- [ ] #25318
- [ ] https://github.com/vector-im/element-web/issues/25320
- [ ] https://github.com/vector-im/crypto-internal/issues/124
```

**Comment by richvdh** [comment]
This seems to have been done months ago!
