### ISSUE TITLE
Element-R: login-and-verify tranche 1: groundwork

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#24983]
* [x] #25429
  * Create a “bot” account with bootstrapped cross signing
  * Log into the same account
  * In “Verify this device”, choose “Verify with another device”
  * Go through the verification process with SAS.
  * At the end, download the device keys and check that it is cross-signed.
  Estimate: 2d
  https://github.com/matrix-org/matrix-react-sdk/pull/10940

* [x] https://github.com/vector-im/crypto-internal/issues/94 Repeat for QR code. 

* [x] https://github.com/vector-im/crypto-internal/issues/95 Extract interface for `VerificationBase` 
   * `TypedEventEmitter`
   * `verify`
   * `cancel`
   * Some way of pulling out `sasEvent` and `reciprocateQREvent` that doesn’t require casting. Likely just `getSasEvent`/`getReciprocateQREvent` methods, which can return null.
   Use new VerificationBase interface in VerificationPanel.
   Estimate: 1d

  https://github.com/matrix-org/matrix-js-sdk/pull/3414 / https://github.com/matrix-org/matrix-react-sdk/pull/10996

* [x] https://github.com/vector-im/crypto-internal/issues/96 Extract a new interface from `crypto/verification/request/VerificationRequest`, implementing a minimal API. We will need:
  * `TypedEventEmitter<VerificationRequestEvent.Change>`
  * `phase` (maps to [VerificationRequest::state](https://matrix-org.github.io/matrix-rust-sdk/matrix_sdk_crypto/struct.VerificationRequest.html#method.state))
  * `accept`
  * `otherUserId`
  * `isSelfVerification`
  * `otherPartySupportsMethod`
  * `verifier`, which should return the new VerificationBase interface
  * No doubt lots of others
  Use new VerificationRequest interface in:
  * `VerificationPanel`
  * `EncryptionPanel`
  * `VerificationRequestDialog`
  Estimate: 2d
  https://github.com/matrix-org/matrix-js-sdk/pull/3449, https://github.com/matrix-org/matrix-react-sdk/pull/11050

* [x] https://github.com/vector-im/crypto-internal/issues/97 `MatrixClient.getVerificationRequestsToDeviceInProgress`: add to `CryptoApi`, returning the new `VerificationRequest`. Deprecate the old one. Stub out in `RustCrypto` for now.
  Estimate: 0.25d

* [x] https://github.com/vector-im/crypto-internal/issues/98 `MatrixClient.requestVerification(my_user_id)`: add to `CryptoApi`, returning the new `VerificationRequest` interface. Call it `requestVerificationToDevice` for symmetry with `requestVerificationDM`. Stub out in `RustCrypto` for now.
Estimate: 0.25d

* [x] https://github.com/vector-im/crypto-internal/issues/99 Js-sdk integration tests:
  We should write some integ tests, and run them on both legacy and Rust crypto. (There exist some unit tests which we may be able to use for inspiration, but they are a bit granular, and are built around TestClient)
  * Call requestVerificationToDevice. Check that a to-device is sent, and check that getVerificationRequestsToDeviceInProgress returns it
  * Walk through the happy path
  Estimate: 1d to set up a test of the happy path
