### ISSUE TITLE
OIDC: Log out

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#25394]
Ensure that we are able to log out when logged in using OIDC. Refer to the [Client Implementation Guide](https://areweoidcyet.com/client-implementation-guide/) for more info.
```[tasklist]
### Tasks
- [ ] https://github.com/vector-im/element-web/issues/25708
- [ ] https://github.com/vector-im/element-web/issues/25710
- [ ] https://github.com/vector-im/element-web/issues/25709
- [ ] OIDC: Kill device with homeserver (?)
- [x] Soft logout?
```
