### ISSUE TITLE
OIDC: Log in

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#25392]
## Summary

Support login via native OIDC in Element Web. Refer to https://areweoidcyet.com/client-implementation-guide/ for guidance. (You will need to find out what OIDC is before you can understand it.)

You will almost certainly need to break this story up into smaller parts before implementing it.

### Discovering homeserver support

Currently, Element Web is an "[OIDC-aware](https://github.com/matrix-org/matrix-doc/pull/3824)" client, which means it has some slight alterations to its existing SSO login flow that make OIDC work a little better, but it doesn't take full advantage of OIDC.

Currently, to discover that a homeserver supports OIDC, we examine the list of available login flows (see [Login.ts](https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/Login.ts#L81)) and if we find a OIDC one masquerading as an SSO flow, we only display that.

Instead of this, before we ask the homeserver what flows it supports, we should check the `.well-known` info we have back from the homeserver, and if it contains the `m.authentication` section with the info we need as described in [MSC2965](https://github.com/matrix-org/matrix-spec-proposals/pull/2965), then use that to find what we need.

This means we must fetch another `.well-known` file from the `issuer` we got from the `m.authentication` server, and look inside that for the `authorization_endpoint`. Now, I (@andybalaam) think we have what we need to delegate directly to the authorization endpoint without asking the homeserver what auth flows it supports. This means we can jump directly to redirecting to that endpoint, somewhere near [BasePlatform.ts startSingleSignOn](https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/BasePlatform.ts#L342).

The guiding MSC for this work is [MSC2964](https://github.com/matrix-org/matrix-spec-proposals/pull/2964), but the specifics you need here are in [MSC2965](https://github.com/matrix-org/matrix-spec-proposals/pull/2965).

I suspect the changes will be limited to [Login.ts](https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/Login.ts#L81), [BasePlatform.ts](https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/BasePlatform.ts#L342) and nearby code. (But I am not certain -- @andybalaam)

This part corresponds to the first Requirement of [OIDC Native clients](https://areweoidcyet.com/#clients) - "Discovery of OP in /.well-known/matrix/client". Refer to the [Client Implementation Guide](https://areweoidcyet.com/client-implementation-guide/) for more info. It may also correspond to the second part - I'm not sure which Web UI is meant there - the login one or something else (e.g. signup or administration).

### Dynamic and static client registration

We should support both dynamic and static client registration. See "Discovery and client registration" in https://areweoidcyet.com/client-implementation-guide/ 

```[tasklist]
### Subtasks
- [x] Add a config flag for use during development
- [ ] https://github.com/vector-im/element-web/issues/25466
- [ ] https://github.com/vector-im/element-web/issues/25467
- [ ] https://github.com/vector-im/element-web/issues/25468
- [ ] https://github.com/vector-im/element-web/issues/25472
- [ ] https://github.com/vector-im/element-web/issues/25574
- [ ] https://github.com/vector-im/element-web/issues/25656
- [x] Document new config options in EW
- [ ] https://github.com/vector-im/element-web/issues/25657
- [ ] https://github.com/vector-im/element-web/issues/25665
```
