### ISSUE TITLE
OIDC: Refresh token

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#25444]
When logged in using OIDC, our access token will expire very often (possibly every 5 minutes).

So, we should detect when that has happened and:

* refresh the access token using the refresh token
* retry the request

This should be invisible to the user unless either of those steps fails.

We think/hope there is a single place in the code where all authenticated requests go through, so hopefully these changes can focus in that area.

Refer to https://areweoidcyet.com/client-implementation-guide/ for more info.
```[tasklist]
### Tasks
- [ ] https://github.com/vector-im/element-web/issues/25708
- [ ] https://github.com/vector-im/element-web/issues/25749
- [x] Propose solution to web team
- [ ] https://github.com/vector-im/element-web/issues/25839
- [ ] Proactively refresh tokens (?)
```

**Comment by weeman1337** [comment]
@andybalaam can you triage this issue? I don't really know what to do with it.
