### ISSUE TITLE
Compound adoption

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-web#25486]
## Overview

Meta-issue to help discuss and capture decisions on:

* Element Web adopting Compound Web to further usability and accessibilty targets *reliably*, reducing risk of future regressions
* Using Element Web to guide real-world Compound Web component scope and implementation
* Scrutinising & iterating on Element Web in a customer & strategically informed way - reducing complexity and time to market on execution

This issue aims to provide a lens to cross-team collaboration and unknowns, complimenting the [Compound components board](https://github.com/orgs/vector-im/projects/52/views/18).

## Adoption plan

We'll port Element Web area by area as means to (1) guide component scope and implementation with real-world considerations (2) provide a harmonious enough app-wide experience for users while we make progress and ship (3) provide focus (4) align critical thinking and context switching with other teams and projects:

1. https://github.com/vector-im/internal-planning/issues/438
2. Timeline: ...
3. Composer: ...
4. Room list & Space panel: ...
5. Settings: ...
6. Interstitial journeys: ...

## Known unknowns

A list of cross-team unknowns to work through as we adopt by area:

```[tasklist]
### Tasks
- [ ] https://github.com/vector-im/internal-planning/issues/432
- [ ] https://github.com/vector-im/internal-planning/issues/434
- [ ] https://github.com/vector-im/internal-planning/issues/435
- [ ] https://github.com/vector-im/internal-planning/issues/436
```
