### ISSUE TITLE
[Epic] Compound + WAT: Foundations

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#25546]
This epic tracks the first steps at adopting Compound to the Element web based product.  Is is considered complete when we have done the following: 

```[tasklist]
### Scope
- [ ] https://github.com/vector-im/internal-planning/issues/450
- [ ] https://github.com/vector-im/element-web/issues/25547
- [ ] https://github.com/vector-im/element-web/issues/25548
```

```[tasklist]
### Out of scope
- [ ] Iconographic pass
```

### Time sheeting

Project: `Accessibility`

**Comment by daniellekirkwood** [comment]
@t3chguy assigning this epic to you as you will be tech lead for WAT :D 

Let me know if you want to expand this milestone or discuss it in more detail

**Comment by germain-gg** [comment]
Closing as we've completed all items in scope.
