### ISSUE TITLE
Migrate from Weblate to Localazy for translations

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-web#25608]
The Element X apps integrate with https://localazy.com instead of Weblate. This choice was made, among others, for ease of setup, better support for plural formats and multi-repo translation projects. For consistency and to enable string reuse, we'll be migrating Element Web to Localazy as well.

```[tasklist]
### Tasks
- [x] Research Localazy capabilities for community contributors (we'll want to lock down contributions during the migration but open them up again ASAP afterwards)
- [ ] https://github.com/matrix-org/matrix-web-i18n/pull/7
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/11417
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/11412
- [ ] https://github.com/vector-im/element-web/pull/25970
- [ ] https://github.com/vector-im/element-desktop/pull/1172
- [ ] https://github.com/matrix-org/matrix-web-i18n/pull/9
- [ ] https://github.com/matrix-org/matrix-spec/pull/1620
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/11429
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/11422
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/11436
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/11427
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/11428
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/11434
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/11435
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/11437
- [x] Look for reuse opportunities with Element X strings (probably enough to cross check their `action_*` and `common_*` strings, see https://github.com/vector-im/element-x-android/blob/develop/tools/localazy/README.md)
- [ ] https://github.com/vector-im/element-web/pull/26021
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/11443
- [ ] https://github.com/matrix-org/matrix-web-i18n/pull/10
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/11438
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/11439
- [x] Update docs for developers (https://github.com/vector-im/element-web/blob/develop/docs/translating-dev.md)
- [x] Update docs for contributors (https://github.com/vector-im/element-web/blob/develop/docs/translating.md)
- [x] Remove Element Web project(s) from Weblate
- [x] Remove weblate webhooks
- [x] Update docs for release captain (https://gitlab.matrix.org/new-vector/internal/-/wikis/Element-Web:-Release-Candidates
- [x] Replace Weblate graph in https://github.com/vector-im/element-web/blob/develop/README.md
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/11685
- [x] Migrate all strings to use dedicated keys (hard to script because that wouldn't allow you to build a sensible key hierarchy)
- [x] Set up Element Web project(s) in Localazy and import all strings
- [x] Open Localazy up for contributors
- [ ] https://github.com/matrix-org/matrix-authentication-service/pull/1962
- [x] Document admittance process for Element employees (how to invite contributors, what role to give them, which locales to give them and which not), might have to be centralized for all of Element
- [x] Close https://github.com/vector-im/customer-retainer/issues/21 and the PSB issue linked from there
```

### Time sheeting ⏱️

`RETAINER: ...you know which one...`

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/element-web/issues/21308

**Comment by t3chguy** [comment]
Worth noting currently we rely on Weblate to prune non-english i18n files when a key is removed from the english (base) file

**Comment by Glandos** [comment]
I know that migration is nearly done, but here are some pain points, as a translator:
- Onboarding is difficult: create a localazy account, ask access to language in https://matrix.to/#/#element-translations:matrix.org then accept invitation, then re-notify room to get access.
- Access to other languages is forbidden: it seems that localazy has no "read-only" access. This really helpful to see the current state of translations, what other translators did to solve some issue
- Keyboard shortcut are far from complete: to fill a suggestion, it is required to blur translation input with `ESC`, then insert with `SHIFT+1` (or `2`, `3`, etc.). But refocusing input can only be done either with tabbing like a monkey, since `/` triggers my browser find feature instead of focusing input.
- Keyboard shortcut, reloaded: placeholders, such as `%(value)` are hard to type. In Weblate, shortcuts `CTRL+1` (`2`, `3` for more) insert placeholder at cursor location. It seems only possible to click on the placeholder in Localazy, this is a hard TMS trigger.

**Comment by t3chguy** [comment]
@Glandos can you open a discussion in https://github.com/vector-im/element-meta/discussions

I agree with everything you said, unfortunately we're just following in the footsteps of the Element X Mobile teams here so their input on your concerns is vital for any change to happen

**Comment by Glandos** [comment]
Done in https://github.com/vector-im/element-meta/discussions/2134
