### ISSUE TITLE
Element-R: Cross-user verification

### ISSUE THREAD

**Issue by florianduros** [vector-im/element-web#25752]
https://docs.google.com/document/d/18LuSmlaoeZpsOsiPKIdAxKYsbr9V1etMAYm2vxMId7A/edit#heading=h.ru8oinr04fz7
```[tasklist]
### Tasks
- [ ] https://github.com/matrix-org/matrix-js-sdk/pull/3601
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/11292
- [ ] https://github.com/matrix-org/matrix-js-sdk/pull/3641
- [ ] https://github.com/matrix-org/matrix-js-sdk/pull/3643
- [ ] https://github.com/matrix-org/matrix-js-sdk/pull/3646
- [ ] https://github.com/matrix-org/matrix-js-sdk/pull/3649
- [ ] https://github.com/matrix-org/matrix-js-sdk/pull/3650
- [ ] https://github.com/matrix-org/matrix-js-sdk/pull/3691
- [ ] https://github.com/matrix-org/matrix-react-sdk/pull/11364
- [ ] Enable cypress tests to run with rust-crypto
- [ ] https://github.com/vector-im/crypto-internal/issues/148
```
