### ISSUE TITLE
UI issues with the v1 dark theme (pre-redesign)

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#2988]
"Issues" being a loose term. This is intended to be a collection of hard-to-see and similar oddities in the dark theme.

Edit: Reference #2984 
Edit: I'll try to keep this list updated as issues are fixed/added

------

* [x] Markdown code blocks
![capture](https://cloud.githubusercontent.com/assets/1190097/22088188/7d2c56d6-dd9f-11e6-9c9a-b348c92198fe.PNG)

* [x]  "Unencrypted room" indicator
   * [x] ![capture](https://cloud.githubusercontent.com/assets/1190097/22088201/8d4c7c58-dd9f-11e6-89af-88255f0d9302.PNG)
   * [x] ![image](https://cloud.githubusercontent.com/assets/1190097/26469373/fe43d382-4156-11e7-9148-1f118b3cc054.png)
   * [x] https://github.com/vector-im/riot-web/issues/2988#issuecomment-308164113

* [x]  Chrome - Doesn't play nice when changing the theme for the first time
Fixed via https://github.com/matrix-org/matrix-react-sdk/commit/a88f9fdd73095c03423f2c5d649ea4930aa55b0a

*  [x] Context menu on a message
![capture](https://cloud.githubusercontent.com/assets/1190097/22088434/37d1829e-dda1-11e6-84d9-121642895a5f.PNG)

*  [x] Radio buttons are hard to see in Chrome (I'm not sure there's much that can be done, however)
![capture](https://cloud.githubusercontent.com/assets/1190097/22088575/4d288024-dda2-11e6-9980-72f7fa261161.PNG)

* [x] [Currently opened room's background color is pure black](https://github.com/vector-im/riot-web/issues/2988#issuecomment-273642997)
* [x] [Icon overlay on room hover doesn't match the theme very well](https://github.com/vector-im/riot-web/issues/2988#issuecomment-273642997)
* [x] [Light background menus hard to see](https://github.com/vector-im/riot-web/issues/2988#issuecomment-273684561)
* [x] [Start chat dialog text field](https://github.com/vector-im/riot-web/issues/2988#issuecomment-273862350)
* [x] Icons too dark [1](https://github.com/vector-im/riot-web/issues/2988#issuecomment-273897164) | [2](https://github.com/vector-im/riot-web/issues/2988#issuecomment-273929099) | [3](https://github.com/vector-im/riot-web/issues/3433)
* [ ] [Scrollbars don't match theme](https://github.com/vector-im/riot-web/issues/2988#issuecomment-274168454)
* [x] Invite selector too light [1](https://github.com/vector-im/riot-web/issues/2988#issuecomment-276395054) [2](https://github.com/vector-im/riot-web/issues/3213)
* [x] [Manage integration dialog](https://github.com/vector-im/riot-web/issues/2988#issuecomment-277003663)
* [x] [Rich Text Editor](https://github.com/vector-im/riot-web/issues/2988#issuecomment-277289616)
* [ ] [Logout woes](https://github.com/vector-im/riot-web/issues/2988#issuecomment-277292210)
  * [ ] [Prefix/placeholder assists](https://github.com/vector-im/riot-web/issues/2988#issuecomment-299898238) on login page
* [x] [Caching woes](https://github.com/vector-im/riot-web/issues/2988#issuecomment-277294228)
* [x] [Room does not exist warning](https://github.com/vector-im/riot-web/issues/2988#issuecomment-278039692)
* [x] [Tables (markdown)](https://github.com/vector-im/riot-web/issues/2988#issuecomment-278417215)
* [x] Selected text is hard to see - https://github.com/vector-im/riot-web/issues/3140
* [x] File upload icon is broken (?) - https://github.com/vector-im/riot-web/issues/3138
* [x] Queued vs sent message diff not working - https://github.com/vector-im/riot-web/issues/3134
* [x] Voip bar - https://github.com/vector-im/riot-web/issues/3182
* [ ] RTE Markdown indicator unclear - https://github.com/vector-im/riot-web/issues/3208
* [x] White halos on avatars - https://github.com/vector-im/riot-web/issues/3203
* [ ] Vertical scrollbar on wide code blocks falls behind text, leading to zebra stripes
  ![vert scrollbar](https://cloud.githubusercontent.com/assets/1190097/23310537/1c72ae38-fa70-11e6-9e0d-9039879decf0.PNG)
* [x] Kick (and presumably ban) dialog reason text entry https://github.com/vector-im/riot-web/issues/3927 and https://github.com/vector-im/riot-web/issues/3927
  ![image](https://cloud.githubusercontent.com/assets/1190097/23311536/a942536a-fa73-11e6-956d-64ea49b6ca19.png)
* [x] Dark tint makes buttons look disabled - https://github.com/vector-im/riot-web/issues/3328
* [x] Redactions
   ![image](https://cloud.githubusercontent.com/assets/1190097/23756937/98cd7e2c-04a2-11e7-9e7d-21688c87e30d.png)
* [x] Unread messages banner - https://github.com/vector-im/riot-web/issues/3783
* [x] Quoted text/url previews makes things look like gaps. https://github.com/vector-im/riot-web/issues/3393
* [ ] [Quoted text is hard to read](https://github.com/vector-im/riot-web/issues/5154)
* [ ] Room directory join icon too dark https://github.com/vector-im/riot-web/issues/3349
* [x] new code block coloring https://github.com/vector-im/riot-web/issues/4444
* [ ] [close icons hard to see](https://github.com/vector-im/riot-web/issues/2988#issuecomment-313205493)
* [x] changelog text hard to read https://github.com/vector-im/riot-web/issues/4637
* [ ] [IRC bridged colors hard to see](https://github.com/vector-im/riot-web/issues/2988#issuecomment-318893316)
* [ ] [Autocomplete field not themed](https://github.com/vector-im/riot-web/issues/5690)

**Comment by alexmat2on** [comment]
In the following screenshot, there are two issues:

1) The currently opened room's background color is pure black, which looks out of place with the slate/dark grey of everything else. The selected room should be darker than the others, but not *that* dark. In the screenshot, I have #riot open.

2) When you hover over other rooms, the room icon gets an overlay to indicate it's being hovered on. The overlay seems to be too light though, (i.e., it lightens the room icon) which also feels out of place in the dark theme. Perhaps darkening would work better. In the screenshot, I'm hovering over #matrix. 

![dark theme issues](https://cloud.githubusercontent.com/assets/8573120/22088336/4eff8d0c-ddb1-11e6-8cea-a450146bb246.png)

**Comment by turt2live** [comment]
Another case: Ping notifications are a bit harsh on the eyes.
![image](https://cloud.githubusercontent.com/assets/1190097/22091015/ca6e5aea-ddb1-11e6-8437-2a85c5735ccc.png)

**Comment by alexmat2on** [comment]
The light-grey text on white background in these sorts of menus is a little hard to read:

![2light1](https://cloud.githubusercontent.com/assets/8573120/22094634/b5b05f60-dddc-11e6-93de-e34e62bae5ac.png)
![2light2](https://cloud.githubusercontent.com/assets/8573120/22094633/b5b05c22-dddc-11e6-971e-43e822f4b9dd.png)

**Comment by turt2live** [comment]
Start chat dialog (Chrome).

![image](https://cloud.githubusercontent.com/assets/1190097/22120443/f31245fc-de3c-11e6-80ad-86bc41c71a7d.png)

**Comment by turt2live** [comment]
Mute icon under the room's context menu for notifications
![image](https://cloud.githubusercontent.com/assets/1190097/22125117/af146a8e-de4f-11e6-9089-8413944e2299.png)

**Comment by ara4n** [comment]
dark icons in general are too dark - e.g. padlock, close-buttons, photo button on User Settings.

thanks for enumerating all these (and continuing to do so); will get them all sorted before we release it.

**Comment by ara4n** [comment]
* [ ] non-Gemini scrollbars are too light:

<img width="531" alt="screen shot 2017-01-20 at 20 11 00" src="https://cloud.githubusercontent.com/assets/1294269/22163895/b90f5fe6-df4c-11e6-972c-b91dc1cbc6bd.png">

* [ ] ...and gemini ones are too dark:

**Comment by ara4n** [comment]
* [ ] selector when inviting is white-on-white

**Comment by turt2live** [comment]
* [ ] Manage integrations dialog - close button, text, icons
![image](https://cloud.githubusercontent.com/assets/1190097/22557662/6c39d13e-e928-11e6-8d69-13522b6ca6d2.png)

**Comment by turt2live** [comment]
* [ ] RTE
![image](https://cloud.githubusercontent.com/assets/1190097/22598480/def2e2d8-e9f0-11e6-87c9-e7fa58e2aae5.png)

Steps:
1. Enabled RTE
2. Clicked bold (without text in field)

Entering text after the asterisks causes it to be readable, however backspacing back to the asterisks causes the same effect as above.

**Comment by turt2live** [comment]
* [ ] Logging out of an account that had the dark theme enabled. (This is post-logout, no page refresh)
![image](https://cloud.githubusercontent.com/assets/1190097/22598941/52f7b39c-e9f2-11e6-8469-e19f5a4fd250.png)

**Comment by turt2live** [comment]
* [ ] Some images end up caching to the light version for long-time light theme users (or those starved of having the dark theme until recently). 
![image](https://cloud.githubusercontent.com/assets/1190097/22599231/56b50114-e9f3-11e6-9ac5-f140a6f83dee.png)

*This is probably a non-issue in a way.*

**Comment by turt2live** [comment]
* [ ] Join room 'room does not exist' message
![image](https://cloud.githubusercontent.com/assets/1190097/22698462/d71d9fa2-ed11-11e6-9af7-1b71ed04e35c.png)

**Comment by turt2live** [comment]
* [ ] Markdown tables
![image](https://cloud.githubusercontent.com/assets/1190097/22751326/2f9534e4-edf1-11e6-9fa5-31b746deb517.png)
https://matrix.to/#/!UcYsUzyxTGDxLBEvLz:matrix.org/$1486578180361WpSMO:safaradeg.net (`#offtopic`)

**Comment by lukebarnard1** [comment]
`mx_Login_field_prefix`, `mx_Login_field_suffix` background colour

![2017-05-08-161844_530x583_scrot](https://cloud.githubusercontent.com/assets/6750344/25811193/53dd5ade-340a-11e7-93cf-07b106c2da8d.png)

**Comment by turt2live** [comment]
For those not watching this aggressively, I've updated the OP.

**Comment by t3chguy** [comment]
I think `"Unencrypted room" indicator` is done now. It was an ambiguous inconsistency, one of my first PRs :P
![image](https://user-images.githubusercontent.com/2403652/26969295-2d420382-4cfd-11e7-867c-765faaf870e1.png)

**Comment by tessgadwa** [comment]
@t3chguy are you still working on this theme?

**Comment by t3chguy** [comment]
Me? Working on this theme? I fixed any issues that hurt my eyes is all :P
I have 0 UI skillz

**Comment by tessgadwa** [comment]
Cool. I've been wanting to dive back in, but a little discouraged since my PR for the light contrast theme never completed review.

**Comment by ara4n** [comment]
the light contrast theme is still on my radar; we are just drowning in PRs and releases atm.  I haven't forgotten it.

**Comment by turt2live** [comment]
@t3chguy there's two icons for the encrypted icon, the one you mention is fixed:
![image](https://user-images.githubusercontent.com/1190097/26996986-8a551d9e-4d33-11e7-89d4-4ca4a041bfdf.png)

**Comment by t3chguy** [comment]
ah @turt2live I must've missed it
that one is plainly missing an invert, I will sort it

**Comment by t3chguy** [comment]
@turt2live sorted :)

**Comment by t3chguy** [comment]
@alexmat2on thats just the browser's native tooltip and afaik we have no control over that, we could spawn our own tooltips but imho thats a little silly

**Comment by tessgadwa** [comment]
thanks @ara4n  all good.

**Comment by turt2live** [comment]
Encrypted room icon in room settings is purple now...
![image](https://user-images.githubusercontent.com/1190097/27091860-a54a48c0-501e-11e7-9b17-e5e880ca31e8.png)

**Comment by t3chguy** [comment]
oh heck, I guess it should only have the flipColour class when its unlocked. I shall fixy @turt2live

**Comment by uhoreg** [comment]
- [ ] "X" icon when viewing user is hard to see ![](https://matrix.org/_matrix/media/v1/download/matrix.org/affZHbGhFWgcfByfqxXGOPmr) (as reported by jgkamat at https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$14992830915197160WLwNO:matrix.org)

**Comment by grahamperrin** [comment]
## Texts: legibility of dark blue and other troublesome colours on the dark grey background

Borrowed from issue `4403`:

![2017-07-30 11 03 35 without mx_roomheader_avatar](https://user-images.githubusercontent.com/192271/28752598-7cd39028-751b-11e7-95ba-020705037fc2.png)

Troublesome colours include: 

- dark blue (e.g. the word _Shrustika_) 
- mid blue (e.g. _geraldobarros_)
- red (e.g. _michaelkohler_)
- purple (e.g. _karanganesan_ and _Jandit_).

### Related

[Optionally include higher contrast colour scheme · Issue #2300 · vector-im/riot-web](https://github.com/vector-im/riot-web/issues/2300)

**Comment by Mikaela** [comment]
@grahamperrin I think that is an issue with the bot using those colours rather than Riot as I think it would also affect many IRC clients with dark backgrounds.

**Comment by grahamperrin** [comment]
With a different bot, a different troublesome colour (darker purple, I think): 

![2017-08-02 18 58 45](https://user-images.githubusercontent.com/192271/28887644-d91ebaf0-77b5-11e7-9337-a24dbd7bfd81.png)

Should there be separate issues for each bot?

**Comment by t3chguy** [comment]
@grahamperrin the bot related issues should probably end up in their respective repository

**Comment by aidalgol** [comment]
The `mx_filterFlipColor` apprach seems to me to put the logic in the wrong place.  Why not instead select these same elements, by their semantic names, in the SCSS code, instead of making styling decisions in the components?

**Comment by grahamperrin** [comment]
label: _redesign_, https://github.com/vector-im/riot-web/labels/redesign

**Comment by turt2live** [comment]
The new new dark theme stuff is being tracked here: https://github.com/vector-im/riot-web/issues/8554

**Comment by aaronraimist** [comment]
I don't see anything else in here that is still applicable to the new dark theme

**Comment by ingingin** [comment]
Close this, and replace #8554 on your Roadmap -> 

> SMALL: Implement Black Theme and make dark theme lighter [[issue]](https://github.com/vector-im/riot-web/issues/2988)

I actually believe adding this to `First Time User Experience` roadmap would be better. The current Dark Theme doesn't look good. Example; the lines 
![image](https://user-images.githubusercontent.com/65529926/84151240-9742d080-aa52-11ea-8798-f56c32565713.png)
![image](https://user-images.githubusercontent.com/65529926/84151322-b80b2600-aa52-11ea-8a82-e67966540ae0.png)

And the loading, as said before. But the outlines around the loading box doesn't have the harsh lines which should be default everywhere :+1: 
![image](https://user-images.githubusercontent.com/65529926/84151639-310a7d80-aa53-11ea-8f78-4f3ea9dfdbeb.png)

**Comment by yannicka** [comment]
1. https://github.com/vector-im/riot-web/issues/2988#issuecomment-313205493 seems to be fixed
2. Checkboxes "Autocomplete field not themed" and "Room directory join icon too dark #3349" can be checked

**Comment by turt2live** [comment]
I'm closing this as it is now 2 brands old and isn't really in a useful format by today's standards - please open new issues for each issue, though preferably they are zoned for the design team to take a look when they encounter the area.
