### ISSUE TITLE
@Mentions TODO

### ISSUE THREAD

**Issue by lukebarnard1** [vector-im/element-web#4640]
So far, mentions look like this:

![2017-07-24-170223_497x252_scrot](https://user-images.githubusercontent.com/6750344/28533362-b4f863b0-7094-11e7-933d-21b3232fb24a.png)

There are a few things left to do on them before we release:
 
  - [ ] Rooms that the client hasn't seen are not populated with an avatar. **EDIT:** this is non-trivial because there isn't an API for #room-alias -> room avatar. The directory stuff could be modified to work for exact matches on the alias, but ultimately this is a spec/server change.
- [x] Various issues with `/commands` #4762
- [x] Draft-js has a bug that has caused quoting to regress. https://github.com/matrix-org/matrix-react-sdk/pull/1279
- [x] `/join #alias` doesn't work if the operand is tab-completed https://github.com/vector-im/riot-web/issues/4676 matrix-org/matrix-react-sdk#1254
- [x] When autocompleting, insert MD entity `(#someroom)[https://matrix.to/...]` (Pills should not display the completions inserted, but rather the actual room alias / user display name) https://github.com/matrix-org/matrix-react-sdk/pull/1238
- [x] Users who aren't in the room that they are mentioned in should have their pill populated using `/profile` API (https://github.com/matrix-org/matrix-react-sdk/pull/1246)
- [x] Unknown rooms in the timeline should look the same as unrecognised rooms in the RTE these should look like links. 
- [x] Don't send MD mentions of users in plaintext body (https://github.com/matrix-org/matrix-appservice-irc/issues/477). This will effectively mean stripping out markdown links before sending if they match the matrix.to user URL and leaving the textual contents. (https://github.com/matrix-org/matrix-react-sdk/pull/1242)
- [x] When populating timeline pills, prevent abuse by always inserting known display names for users and canonical aliases for rooms this is now done by the composer (https://github.com/matrix-org/matrix-react-sdk/pull/1238) but we should also do this in the timeline.
- [x] Clicking someone still inserts the plain "someone:" https://github.com/matrix-org/matrix-react-sdk/pull/1239
- [x] Mention highlighting https://github.com/matrix-org/matrix-react-sdk/pull/1234
![2017-07-19-110426_777x100_scrot](https://user-images.githubusercontent.com/6750344/28361855-1558dd60-6c72-11e7-8c53-71e04013ff77.png)
- [x] Fix the kerning matrix-org/matrix-react-sdk@ccf5d6f

**Comment by ara4n** [comment]
Some more thoughts:
 * [ ] The space between the avatar and the first letter of the pill should be increased by 1px
 * [ ] Mentions without a pill should have the spacing of the pill removed entirely (to spell out the 'fix the kerning' issue above) to avoid it adding in lots of whitespace
 * [ ] If the first thing you type in the composer is a mention, one should still append `: ` to it, like we used to pre-RTE
 * [ ] We should probably have an option in UserSettings to hide avatars from mentions in the timeline - I can see the hardcore IRC contingent getting distraught at having little faces everywhere...

**Comment by t3chguy** [comment]
it seems like seequ means that rooms which were not known by the recipient were not made into pills

**Comment by ara4n** [comment]
* [] Consider removing disambiguation when rendering pills?  (We'd keep it in the line format for compatibility with clients which don't understand mentions, but when we render the mention we could replace it with the current displayname for the user, and rely on hoverovers for disambiguation - a bit like we will be doing for flair)
* [] Show pills for rooms even if the receiving client doesn't know about the existence of that room (seequ's bug mentioned above by @t3chguy)

**Comment by uhoreg** [comment]
> Consider removing disambiguation when rendering pills?

One possible way to do that is to wrap the disambiguation in a span with a special class (e.g. `<a href="https://matrix.to/...">uhoreg<span class="mxid_disambiguation"> (@uhoreg:matrix.org)</span></a>`), so that clients that understand the new mention syntax can just `span.mxid_disambiguation { display: none; }`

**Comment by turt2live** [comment]
other options could be to make it an attribute on the pre-existing node, or to just throw it into the event content (although that might be a bit dirty?)

**Comment by lukebarnard1** [comment]
To prevent abuse, we should be replacing the text content of the mentions with the actual display name or room alias of the resource linked anyway. It would be at that point where we would consider not inserting the disambiguation.

In terms of the implementation,
> wrap the disambiguation in a span with a special class 

would be done at the point we insert the disambiguation (after the message has been received) so perhaps we could just not insert it (and make that conditional on a user setting perhaps?) Not to mention allowing certain `class` names would be a bit weird during sanitisation.

>make it an attribute on the pre-existing node, or to just throw it into the event content (although that might be a bit dirty?)

the receiving client has enough information to do the disambiguation itself so this feels redundant. And yes, quite dirty :stuck_out_tongue:

**Comment by lukebarnard1** [comment]
>We'd keep it in the line format for compatibility with clients which don't understand mentions, but when we render the mention we could replace it with the current displayname for the user, and rely on hoverovers for disambiguation - a bit like we will be doing for flair)

SGTM, and we will be replacing the pill text anyway to prevent abuse.

**Comment by lukebarnard1** [comment]
>arbitrary room aliases.

Does it matter if there's no avatar? Currently there's no API for mapping #alias -> avatar

**Comment by ara4n** [comment]
it's not a huge problem; bit of a shame though.

**Comment by resynth1943** [comment]
I have another problem, but I'm not sure if it's covered (search didn't help):

If you mention people in the composer, then enter another key, the `src` attributes of the mention pills are re-set, making them load again.

I'm relatively sure browsers don't do an identity check on old and new `src` attributes, so any `src` set (regardless of identity) will end up re-requesting the image.

Would anyone like me to take a look at this?
