### ISSUE TITLE
Widget usability improvements

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#5832]
General tracker for HL things we can do to make widgets more usable:
 * [x] Show them expanded by default when you add them to a room
 * [x] Support more than 2 widgets at a time
 * [ ] Make the widgets resizeable (remembering the size requested)
 * [ ] Support maximising/minimising per-widget
 * [x] Rationalise the two buttons (appstore button at the top right, versus 'show widgets' button next to the composer).  I don't think I have ever used the 'show widgets button' in practice in my life.

**Comment by turt2live** [comment]
As a data point: I often forget that the show widgets button exists, and am only reminded of it when someone asks "what does it do?".

**Comment by ara4n** [comment]
the remaining things here are redesign issues

**Comment by turt2live** [comment]
sorry redesign, you missed out on a bunch of options :(

**Comment by TheRealCuran** [comment]
Just a drive-by comment: matrix-org/matrix-react-sdk#4493 sounds related to this ticket. It claims to implement vector-im/riot-web#6785 which sounds a lot like the two remaining points here.

**Comment by turt2live** [comment]
Widgets have changed drastically since this was opened. If any of the concerns are still present, please open a new issue.
