### ISSUE TITLE
Groups over /sync

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#5870]
### Description

This is effectively a tracking issue for having group updates over /sync or a similar mechanism. I'll leave it to the issue-triaging as to whether this (or other) issues should be closed.

* [ ] Group members (invites/joins/leaves) - https://github.com/vector-im/riot-web/issues/5228
* [ ] Accepting/declining invites - https://github.com/vector-im/riot-web/issues/5227
* [ ] Flair/group avatar changes - https://github.com/vector-im/riot-web/issues/5235

### Version information

- **Platform**: web (in-browser)
- **Browser**: Chrome 63
- **OS**: Windows 10
- **URL**: riot.im/develop

**Comment by ara4n** [comment]
I'm a bit confused - isn't https://github.com/matrix-org/synapse/issues/2691 requesting the opposite (i.e. that group updates should *not* happen over /sync?)

**Comment by turt2live** [comment]
They are conflicting in a way. The goal of https://github.com/matrix-org/synapse/issues/2691 was to have a different /sync stream. The goal of this issue is to give people a place to track the issue, given it is highly requested and argued for.

**Comment by turt2live** [comment]
Related: https://github.com/matrix-org/matrix-doc/issues/1222

**Comment by t3chguy** [comment]
This is fixed by Spaces landing in Beta in next Release
