### ISSUE TITLE
Redesign: Remaining bits after both user and room settings are implemented

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#8207]
Part 0 (already fixed prior to grouping):
* [x] Fixed dialog size / scrolling improvements - PR: https://github.com/matrix-org/matrix-react-sdk/pull/2501
* [x] Positive wording for settings (https://github.com/vector-im/riot-web/issues/6435) - PR: https://github.com/matrix-org/matrix-react-sdk/pull/2504
* [x] Transitions on toggle switches - PR: https://github.com/matrix-org/matrix-react-sdk/pull/2505
* [x] Fix https://github.com/vector-im/riot-web/issues/8249 (CSS for disabled selects) - PR: https://github.com/matrix-org/matrix-react-sdk/pull/2502
* [x] Fix https://github.com/vector-im/riot-web/issues/8250 (no placeholders) - PR: https://github.com/matrix-org/matrix-react-sdk/pull/2503
* [x] Fix code style on net-new CSS - PR: https://github.com/matrix-org/matrix-react-sdk/pull/2528
* [x] Fix https://github.com/vector-im/riot-web/issues/8264 (field selects on macOS)

Part 1 (PR: https://github.com/matrix-org/matrix-react-sdk/pull/2526):
* [x] Fix https://github.com/vector-im/riot-web/issues/8265 (riot bot button)
* [x] Improved padding on user preferences tab (and everywhere else)
* [x] Fix colours/sizing of notification settings table
* [x] Fix https://github.com/vector-im/riot-web/issues/8275 (semibold is wrong)

Part 2 (PR: https://github.com/matrix-org/matrix-react-sdk/pull/2549):
* [x] Fix margin on header of settings dialogs
* [x] Fix the Settings title and the modal close X in position
* [x] Other misc stuff to do with the layout of the dialogs (short viewports, long viewports, etc)
* [x] Fix https://github.com/vector-im/riot-web/issues/8328 (escape should escape)
* [x] Fix https://github.com/vector-im/riot-web/issues/8329 (name of room settings)

Part 3 (PR: https://github.com/matrix-org/matrix-react-sdk/pull/2553):
* [x] Publish room to directory button
* [x] Fix https://github.com/vector-im/riot-web/issues/8327 (flair on general tab)
* [x] Fix https://github.com/vector-im/riot-web/issues/8340 (webcam left on)

Part 4 (PR: https://github.com/matrix-org/matrix-react-sdk/pull/2554):
* [x] Removing temporary tab for visiting old settings
* [x] Removing the old user settings entirely
* [x] Removing the old room settings entirely
* [x] Remove labs flag

Priority 2 problems ("would be really nice if..." items):
* [x] Fix https://github.com/vector-im/riot-web/issues/8804 (squished power level options) - PR: https://github.com/matrix-org/matrix-react-sdk/pull/2725
* [x] `EditableItemList` should be using `Field`, not whatever it currently is (aliases, related groups)
  * See https://github.com/vector-im/riot-web/issues/8591
  * Fix https://github.com/vector-im/riot-web/issues/8803
  * PR: https://github.com/matrix-org/matrix-react-sdk/pull/2679
* [x] Fix the need for a `DragDropContext` over the flair settings - PR: https://github.com/matrix-org/matrix-react-sdk/pull/2685
* [x] Fix https://github.com/vector-im/riot-web/issues/8371 (unmount causes return to general tab) - PR: https://github.com/matrix-org/matrix-react-sdk/pull/2724
* [x] Fix https://github.com/vector-im/riot-web/issues/8408 (firefox scrolling) - PR: https://github.com/matrix-org/matrix-react-sdk/pull/2579
* [x] Fix https://github.com/vector-im/riot-web/issues/8440 (textarea disabled not visible) - PR: https://github.com/matrix-org/matrix-react-sdk/pull/2591
* [x] Fix https://github.com/vector-im/riot-web/issues/8406 (localecho on settings) - PR: https://github.com/matrix-org/matrix-react-sdk/pull/2593
* [x] Fix https://github.com/vector-im/riot-web/issues/8434 (alias warning) - PR: https://github.com/matrix-org/matrix-react-sdk/pull/2593
* [x] Fix https://github.com/vector-im/riot-web/issues/8432 (publish room doesn't work) - PR: https://github.com/matrix-org/matrix-react-sdk/pull/2590

Priority 3 problems ("if someone gets bored and has time..." items):
* [x] Fix https://github.com/vector-im/riot-web/issues/5496 ? (Email address notifications)
  * Includes https://github.com/vector-im/riot-web/issues/8424
  * PR: https://github.com/matrix-org/matrix-react-sdk/pull/2727
* [x] Fix https://github.com/vector-im/riot-web/issues/8569 (profile save button) - PR: https://github.com/matrix-org/matrix-react-sdk/pull/2726
* [x] The tabs and the icons look a bit small - PR: https://github.com/matrix-org/matrix-react-sdk/pull/2604
* [x] The default settings font is small, especially next to the relatively large toggles - PR: https://github.com/matrix-org/matrix-react-sdk/pull/2604

Priority 4 problems ("Eventually, we will fix..." items):
* [ ] Fix https://github.com/vector-im/riot-web/issues/8438 (move access_token somewhere else)
* [ ] Fix unit tests for Room Settings (and add more for other settings) - https://github.com/vector-im/riot-web/issues/9005
* [ ] Review 3pid management (https://github.com/matrix-org/matrix-react-sdk/blob/experimental/src/components/views/settings/EmailAddresses.js#L28-L38) - https://github.com/vector-im/riot-web/issues/9004
* [ ] Fix devices table design
  *  Unsquish devices table in security settings
  * Make the devices list less jumpy when you select a checkbox
  * Style the device names in the device list so that they look editable
  * See https://github.com/vector-im/riot-web/issues/8319

**Comment by turt2live** [comment]
@lampholder feedback incorporated into the main post.

On the specific items:
> Hide the theme dropdown (since it can't be changed and looks pretty broken atm [macOS, firefox])

See https://github.com/vector-im/riot-web/issues/8249

> let's move flair to its own tab, not because it makes sense, but because it lets us put a slow-loading bit of UI off the main path

I've opened this as https://github.com/vector-im/riot-web/issues/8268 (as per our discussion)

> Make the devices list less jumpy when you select a checkbox
> Style the device names in the device list so that they look editable

Both of these I've put under "fix the device table design" (it's squishy, and that causes a lot of problems)

**Comment by lampholder** [comment]
Having thought about the device list UI a little over the past few days, I've uploaded my most recent sketch of a cards-based device list https://github.com/vector-im/riot-web/issues/8319

**Comment by lampholder** [comment]
I've also spotted another UX issue - when the flow returns a user to settings after they've diverted elsewhere (via the E2E beta warning modal when enabling encryption in a room, or via the key backup UX when configuring key backup on an account) the user lands on the first page of settings, not the page they were on before.

How easy is this to fix? It's certainly jarring landing on an unexpected page, but I can also see it might be tricky to address quickly.

**Comment by lampholder** [comment]
And one more issue - I don't think it's possible to delete an avatar any more. I'd suggest putting the delete X we have in other places as close as possible to the avatar square.

**Comment by turt2live** [comment]
> How easy is this to fix? It's certainly jarring landing on an unexpected page, but I can also see it might be tricky to address quickly.

I'd rather not fix our dialog system this week, and would classify the problem as Very Hard to fix.

> And another one - can we enable Esc closing the settings modal?

Already planned by proxy for Part 2 fixes.

**Comment by turt2live** [comment]
> I'd suggest putting the delete X we have in other places as close as possible to the avatar square (with the 'Remove Avatar' tooltip we have in the /app build of riot)

We should avoid an X at all costs - it confuses everyone. I'd like to get Nad in on this decision.

**Comment by turt2live** [comment]
Removing avatars is being tracked outside of this: https://github.com/vector-im/riot-web/issues/8456

**Comment by turt2live** [comment]
I'm considering this done enough to take it off my top priority list. The remaining work I've shuffled into "p4" (which is relative to the items on this issue). I've also made a note to come back to it in a few months if we haven't managed to make our way around to it.

**Comment by turt2live** [comment]
I think most of this is now just bugs or things we fixed by changing the design (accidentally and sometimes on purpose). Closing in favour of the already-open issues.

We also don't really use epics like this anymore, so this is potentially lost to time 😬
