### ISSUE TITLE
Dark theme follow up issues

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#8554]

**Comment by nadonomy** [comment]
Awesome! Small stuff,  but:

- E2E icons should use primary/notice colours
- Vertical bar splitting top right icons isn't skinned (should we take the primary icon colour and apply 50% opacity?)
- (+) icons in room list not skinned
- @mention backgrounds not skinned (for now using the room highlight bg would be ok)

**Comment by jryans** [comment]
- [ ] Tweak colors values to v2 from Nad

**Comment by aaronraimist** [comment]
- [ ] Markdown button status appears reversed
![image](https://user-images.githubusercontent.com/5855073/52715628-823f5580-2f62-11e9-962e-1996f561ae04.png)
- [ ] Should there be a more visible vertical line here?
![image](https://user-images.githubusercontent.com/5855073/52715671-a6029b80-2f62-11e9-8b3c-4282927ae568.png)
![image](https://user-images.githubusercontent.com/5855073/52715673-a733c880-2f62-11e9-9baa-2a107f1c8816.png)
- [ ] It would be nice to use a white [m] logo in the room directory
![image](https://user-images.githubusercontent.com/5855073/52715891-33de8680-2f63-11e9-98a1-5e32abd456af.png)
- [ ] Safari scrollbars are dark but (one of the) Firefox scrollbars is light. Which is intended? Is Gemini getting killed before 1.0?

**Comment by Half-Shot** [comment]
Can I chuck in:
- [ ] \<pre\> blocks have black text on a black background
![image](https://user-images.githubusercontent.com/2072976/52719036-b0da2200-2f9c-11e9-8786-9db2f80f5c40.png)

**Comment by turt2live** [comment]
* [ ] https://github.com/vector-im/riot-web/issues/8584
* [ ] https://github.com/vector-im/riot-web/issues/8580

**Comment by anoadragon453** [comment]
- [ ] https://github.com/vector-im/riot-web/issues/8586

**Comment by turt2live** [comment]
* [ ] https://github.com/vector-im/riot-web/issues/8587

**Comment by turt2live** [comment]
* [ ] Widgets blend in with the timeline
![image](https://user-images.githubusercontent.com/1190097/52730441-94c48980-2f78-11e9-8b2f-0fb03613ebc3.png)

**Comment by nadonomy** [comment]
@jryans re widgets blending; they should be using the header background colour

**Comment by Half-Shot** [comment]
(could people put names next to their issues if possible so I don't have to mouse over all of them?)

**Comment by Cadair** [comment]
The spinner looks particularly bad on the dark theme I think. It's got a white line around the edges etc.

![image](https://user-images.githubusercontent.com/1391051/52733123-d6c1ef80-2fb9-11e9-964c-c2bcd5305911.png)

**Comment by Cadair** [comment]
Also, the redacted message bar thing seems much more stark than on the light theme.

![image](https://user-images.githubusercontent.com/1391051/52734001-070a8d80-2fbc-11e9-8a76-66753cb8e887.png)

**Comment by turt2live** [comment]
re: redaction bar. There is a dark theme asset from the old design somewhere.
![image](https://user-images.githubusercontent.com/1190097/52734222-e291bf80-2f81-11e9-8773-cfb003087242.png)

**Comment by jryans** [comment]
- [ ] [make dark names more readable when using dark theme · Issue #8611](https://github.com/vector-im/riot-web/issues/8611)

**Comment by jryans** [comment]
- [ ] [Markdown indicator on dark theme is invisible when in RTE mode · Issue #8637](https://github.com/vector-im/riot-web/issues/8637)

**Comment by nadonomy** [comment]
- [ ] 'back' Chevron in member panel

<img width="401" alt="screenshot 2019-02-14 at 18 31 30" src="https://user-images.githubusercontent.com/4626865/52808860-d3486a00-3086-11e9-9462-21778717666a.png">

**Comment by turt2live** [comment]
* [ ] [Redaction thingy](https://github.com/vector-im/riot-web/issues/8559)
* [ ] [File drop UI](https://github.com/vector-im/riot-web/issues/8663)

**Comment by Cadair** [comment]
Some large code blocks are unreadable:

![image](https://user-images.githubusercontent.com/1391051/52821322-53f56f00-3063-11e9-9eb0-d9e52b01f6df.png)

https://matrix.to/#/!pSKzsvYeCMfoKeaeZc:matrix.org/$1550177025286HfaRh:openastronomy.org?via=cadair.com&via=openastronomy.org&via=matrix.org

**Comment by turt2live** [comment]
* [ ] [Concerns with color scheme being hard on the eyes](https://github.com/vector-im/riot-web/issues/8664)

**Comment by Half-Shot** [comment]
@Cadair https://github.com/vector-im/riot-web/issues/8554#issuecomment-463222141 :)

**Comment by turt2live** [comment]
["INVITED" header in member list](https://github.com/vector-im/riot-web/issues/8679)

**Comment by jryans** [comment]
- [ ] [Member search is impossible to read on dark theme and has no clear button](https://github.com/vector-im/riot-web/issues/8673)

**Comment by progserega** [comment]
Dark theme is very contrast - it is heavy for eyes.
Old dark theme was more nice for eyes. Do you can add third theme with old grey color?
![1](https://user-images.githubusercontent.com/1297163/52913098-33990f00-3306-11e9-9e1b-6710f03b1c2f.png)

**Comment by jryans** [comment]
- [ ] [visibility labels on roomdirectory need to be designed and inverted on dark theme](https://github.com/vector-im/riot-web/issues/8721)

**Comment by jryans** [comment]
- [ ] [Distinguishing rooms with new events is hard in the dark theme](https://github.com/vector-im/riot-web/issues/8729)

**Comment by anoadragon453** [comment]
- [ ] [Code Scrollbars in dark theme are invisible](https://github.com/vector-im/riot-web/issues/9052)

**Comment by SilverWolf32** [comment]
Spinners should _definitely_ be inverted to match the background. I don't know if this is OS X-specific, but on here it looks awful.

![The spinner on a dark background](https://user-images.githubusercontent.com/43831298/56761688-83c0a180-678d-11e9-9a69-d8b630582481.png)

**Comment by SilverWolf32** [comment]
Also, the desktop app's window title bar on OS X is still light, even when using the dark theme. I'm not quite sure whether to put that here or somewhere else, since it's desktop-specific, but it's definitely noticeable, pretty much forcing me to use the client full screen. (The latest OS X has system-wide dark mode, and apps have to explicitly opt in to get dark-themed.)

**Comment by dkasak** [comment]
Username highlights on the dark theme look awful while unselected due to the background colour:

![unselected](https://i.imgur.com/J6lfytK.png)

It's a bit better when selected since it then changes to a grey shade:

![selected](https://i.imgur.com/r1YO6ux.png)

**Comment by Mattwmaster58** [comment]
> Also, the desktop app's window title bar on OS X is still light

This is also the case with Windows

**Comment by t3chguy** [comment]
When inactive yes, when active it matches the theme colour as expected.

![image](https://user-images.githubusercontent.com/2403652/76266424-4a870800-625f-11ea-9760-c9ca6ed02a7c.png)

**Comment by Mattwmaster58** [comment]
@t3chguy, huh, that's strange. Here's a screenshot with the window active:
![Annotation 2020-03-09 192258](https://user-images.githubusercontent.com/26337069/76270686-ad66a800-623b-11ea-8093-f2574d353912.jpg)

```
riot-web version: 1.5.12
olm version: 3.1.3
```

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/76270881-b6bd3800-626e-11ea-8cb7-33cb30b42b08.png)

What does your explorer window look like in comparison?

**Comment by Mattwmaster58** [comment]
Dark - I have windows dark theme on. I have set 'follow system theme set' in riot web settings

![image](https://user-images.githubusercontent.com/26337069/76272373-e8b7a580-6240-11ea-8805-d05cc6a794d9.png)

**Comment by HelderFSFerreira** [comment]
I have the same issue as @Mattwmaster58 on windows 10 with dark mode enabled.

**Comment by MadLittleMods** [comment]
Are we good to close this? I count only 3 remaining unchecked tasks. Two of which need issues if they're still actually problems anyway. And I assume there has been a lot more iteration than linked here.

**Comment by turt2live** [comment]
Yea, I think if there's any remaining issues then independent ones would be best :)
