### ISSUE TITLE
Better CI / Buildkite improvements

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#9019]
Tracker for better CI. We have some homework before we can jump on the BuildKite train, which is currently scheduled as "after 1.0":

* [ ] Draw out a build matrix (X needs to run before Y in project Z)
* [ ] Figure out what we want to accomplish (speed? consistency?)
* [ ] Make Docker containers for things in the matrix if possible (but don't worry too much about them). They'll help a lot with the proper CI implementation.

~~As a fallback, if we run into CI problems before "after 1.0", we can take whatever the Travis CI config is and BuildKite it with help.~~ We did this.

----

Other improvements we should make:
* [x] Timestamps in the logs
* [ ] Make webpack verbose
* [x] Don't install Chrome a billion times

**Comment by turt2live** [comment]
Considering the BuildKite CI is leaving us, and almost all of this is targeted at infrastructure issues in BK, closing.
